# Hipótese 5: O Tempo de Normalização das Portas E as Manutenções Corretivas Realizadas Tem Correlação?

## 1. Contexto e Fundamentação Teórica
As Portas de Plataforma (PSDs) são equipamentos eletromecânicos submetidos a ciclos contínuos de abertura e fechamento (ciclagens) para permitir o embarque e desembarque seguro de passageiros nas estações.

A hipótese operacional central estabelece que o tempo que ela demore para ser normalizadas são as que precisam ser consertadas ou dando problemas mais para frente. Isso nos trará dois dados importantes: tempos pequenos de normalização são exclusivamente portas que tiveram apenas obstrução e caso o tempo de normalização passe de X horas, deve ser consertada. 

---

## 2. Definindo a Questão Investigada
* **Portas e seu tempo de normalização**: O tempo para normalizar/fechar é um tempo em que a porta demora para voltar para seu funcionamento normal, mas há tempos bem grandes (chegando à quase 12h). A ideia é comprarar todas as portas que tiveram o tempo de normalização com os problemas, fazendo uma só planilha e ver se o tempo está relacionado à algum problema ou algo do tipo.

---

## 3. Metodologia de Análise
Para testar a validade da hipótese, os dados brutos de alarmes do sistema de PSDs são processados seguindo as seguintes etapas:
1. Normalização e fazer as planilhas se conversarem

In [66]:
from pathlib import Path
import pandas as pd
import openpyxl

correcao_emergencial = pd.read_excel(
    "../../data/Ordens do SAP - Corretiva emergencial (ZM01).XLSX"
)

correcao_programada = pd.read_excel(
    "../../data/Ordens do SAP -Corretiva programada (ZM02).XLSX"
)

alarmes = pd.read_excel(
    "../../data/Alarmes do sistema de PSD.xlsx"
)

print("Emergencial:", correcao_emergencial.shape)
print("Programada:", correcao_programada.shape)
print("Alarmes:", alarmes.shape)

Emergencial: (10647, 28)
Programada: (1163, 28)
Alarmes: (150003, 7)

In [67]:
display(correcao_emergencial.head())
display(correcao_programada.head())
display(alarmes.head())

,Tipo de Nota,Nota,Ordem,Indisponível,Falha,IQM,Analisada,Comentários Classificação Engenharia,Perfil do catálogo,Descrição,...,Centro de Trabalho Responsável,Sintoma,Objeto,Defeito,Causa,Ação,Data Análise,Hora Análise,Encerram.por Data,Hora de Encerramento
0,Z1,14943931,53954586.0,X,X,NaN,NaN,MI/ NVT1 - AVARIADA,6PSD,PSD PL 01-02 Sem status para o CCO,...,SP04IBUT,LAÇO DE PDM ABERTO,NaN,NaN,NaN,NaN,2025-12-05,17:50:50,NaT,00:00:00
1,Z1,15133619,54145839.0,NaN,NaN,NaN,X,DU,6PSD,PSD - PDM's não abriram PLT02,...,SP04IBUT,TODAS AS PDM DA FACHADA NÃO ABREM,CABEAMENTO,CONTROLADOR PCC COMUNICACAO,ERRO DE COMUNICAÇÃO,RESETADO E TESTADO,2026-03-03,17:48:50,2026-02-27,14:26:36
2,Z1,13894133,52913343.0,NaN,NaN,NaN,X,CF/FALHA COMUNICAÇÃO,6PSD,PSD server s/ status das plataformas,...,SP04IBUT,PSD SERVER COM INDICAÇÃO DE FALHA NA PLA,RACK WCN,SENSOR DESTRAVADO AVARIADO,DESGASTE,RESETADO E TESTADO,NaT,00:00:00,2024-04-18,07:33:25
3,Z1,14713349,53724958.0,X,NaN,NaN,X,NC/ RESET,6PSD,BUT PLT 1 PORTAS NAO ABRIRAM,...,SP04IBUT,TODAS AS PDM DA FACHADA NÃO ABREM,CABO/CONECTORES,SWITCH TRAVADO,DESGASTE,RESETADO E TESTADO,2025-08-14,16:38:16,2025-07-08,04:40:58
4,Z1,14643768,53655728.0,X,NaN,NaN,X,NC/RESET,6PSD,PSD plt 1 - Falha geral de abertura,...,SP04IBUT,PDM NÃO ABRE,CABEAMENTO,BAIXA ISOLACAO,FALHA CBTC,RESETADO E TESTADO,2025-05-29,10:58:06,2025-05-28,14:37:13

,Tipo de Nota,Nota,Ordem,Indisponível,Falha,IQM,Analisada,Comentários Classificação Engenharia,Perfil do catálogo,Descrição,...,Centro de Trabalho Responsável,Sintoma,Objeto,Defeito,Causa,Ação,Data Análise,Hora Análise,Encerram.por Data,Hora de Encerramento
0,Z2,15069252,54081268.0,NaN,NaN,NaN,NaN,NaN,6PSD,Porta PCC-PSD a,...,SP04IBUT,PDM NÃO ABRE,"ESTRUTURA, ACABAMENTO, E ACESSÓRIOS DO P",PORTA DESAJUSTADA,FALTA FIXACAO,FIXADO,NaT,00:00:00,2026-01-25,16:50:18
1,Z2,14647619,53659484.0,NaN,NaN,NaN,NaN,NaN,6PSD,PDMs plat 1 e 2 com falha momentânea.,...,SP04IBUT,MAU CONTATO,SWITCK DE COMUNICAÇÃO,SEM CONEXAO ELETRICA,ERRO DE SOFTWARE,RESETADO E TESTADO,NaT,00:00:00,2025-06-01,04:36:44
2,Z2,14682623,53694340.0,NaN,NaN,NaN,NaN,NaN,6PSD,Rele painel SSE intermitente,...,SP04IBUT,FACHADA PSD SEM ALIMENTAÇÃO,DISPOSITIVO DE PROTECAO,CONVERSOR DE TENSAO AVARIADO,OPERACAO INDEVIDA,SUBSTITUIDO(A),NaT,00:00:00,2025-06-19,05:10:12
3,Z2,14864269,53874165.0,NaN,NaN,NaN,NaN,NaN,6PSD,Multimedidor SSE moldura solta,...,SP04IBUT,ESTRUTURA DANIFICADA,MULTIMEDIDOR,VIDRO QUEBRADO,DESGASTE,SUBSTITUIDO(A),NaT,00:00:00,2025-09-30,14:53:22
4,Z2,13390549,52423535.0,NaN,NaN,NaN,NaN,NaN,6PSD,Volume do P.A baixo.,...,SP04IBUT,SERVIDOR SEM COMUNICACAO,SWITCK DE COMUNICAÇÃO,BAIXA ISOLACAO,FALTA FIXACAO,APERTADO(A),NaT,00:00:00,2023-07-27,13:52:02

,TAG,Horário do Alarme,Estação,Porta,Alarme,Horário da Normalizacao,Tempo de Normalização
0,PSD_FAL_FAL2_PDM09_OBS,2026-05-12 08:16:52.657,FAL,9.0,OBS,2026-05-12 08:16:53.670,"0 dias, 00:00:01"
1,PSD_LUZ_LUZ1_PDM08_OBS,2026-05-12 08:15:09.913,LUZ,8.0,OBS,2026-05-12 08:15:10.917,"0 dias, 00:00:01"
2,PSD_FAL_FAL1_PDM15_OBS,2026-05-12 08:14:06.657,FAL,15.0,OBS,2026-05-12 08:14:07.670,"0 dias, 00:00:01"
3,PSD_LUZ_LUZ1_PDM19_OBS,2026-05-12 08:09:31.930,LUZ,19.0,OBS,2026-05-12 08:09:32.917,"0 dias, 00:00:01"
4,PSD_FRE_FRE1_PDM14_OBS,2026-05-12 08:05:05.830,FRE,14.0,OBS,2026-05-12 08:05:14.847,"0 dias, 00:00:09"

In [68]:
correcao_emergencial = correcao_emergencial[
    ["Local de Instalação", "Início avaria", "Hora início avaria", "Fim da avaria", "Hora do fim da avaria", "Sintoma", "Objeto", "Defeito", "Causa"]
]

correcao_programada = correcao_programada[
    ["Local de Instalação", "Início avaria", "Hora início avaria", "Fim da avaria", "Hora do fim da avaria", "Sintoma", "Objeto", "Defeito", "Causa"]
]

display(correcao_emergencial.head())
display(correcao_programada.head())
display(alarmes.head())

,Local de Instalação,Início avaria,Hora início avaria,Fim da avaria,Hora do fim da avaria,Sintoma,Objeto,Defeito,Causa
0,SP04-6-PSD-BUT,14/11/2025,06:35:28,NaN,00:00:00,LAÇO DE PDM ABERTO,NaN,NaN,NaN
1,SP04-6-PSD-BUT,27/02/2026,07:33:00,27/02/2026,12:00:00,TODAS AS PDM DA FACHADA NÃO ABREM,CABEAMENTO,CONTROLADOR PCC COMUNICACAO,ERRO DE COMUNICAÇÃO
2,SP04-6-PSD-BUT-P1S1,18/04/2024,06:00:00,18/04/2024,07:30:00,PSD SERVER COM INDICAÇÃO DE FALHA NA PLA,RACK WCN,SENSOR DESTRAVADO AVARIADO,DESGASTE
3,SP04-6-PSD-BUT-P1S1,07/07/2025,18:38:00,08/07/2025,03:00:00,TODAS AS PDM DA FACHADA NÃO ABREM,CABO/CONECTORES,SWITCH TRAVADO,DESGASTE
4,SP04-6-PSD-BUT-P1S1-PSSE1,28/05/2025,09:10:00,28/05/2025,10:00:00,PDM NÃO ABRE,CABEAMENTO,BAIXA ISOLACAO,FALHA CBTC

,Local de Instalação,Início avaria,Hora início avaria,Fim da avaria,Hora do fim da avaria,Sintoma,Objeto,Defeito,Causa
0,SP04-6-PSD-BUT,25/01/2026,08:20:00,25/01/2026,09:30:00,PDM NÃO ABRE,"ESTRUTURA, ACABAMENTO, E ACESSÓRIOS DO P",PORTA DESAJUSTADA,FALTA FIXACAO
1,SP04-6-PSD-BUT-P1S1,30/05/2025,09:30:00,01/06/2025,04:00:00,MAU CONTATO,SWITCK DE COMUNICAÇÃO,SEM CONEXAO ELETRICA,ERRO DE SOFTWARE
2,SP04-6-PSD-BUT-P2S1-PSSE2,19/06/2025,02:00:00,19/06/2025,04:30:00,FACHADA PSD SEM ALIMENTAÇÃO,DISPOSITIVO DE PROTECAO,CONVERSOR DE TENSAO AVARIADO,OPERACAO INDEVIDA
3,SP04-6-PSD-BUT-P2S1-PSSE2,30/09/2025,09:00:00,30/09/2025,12:00:00,ESTRUTURA DANIFICADA,MULTIMEDIDOR,VIDRO QUEBRADO,DESGASTE
4,SP04-6-PSD-BUT-PLT1,21/07/2023,14:00:00,27/07/2023,13:50:56,SERVIDOR SEM COMUNICACAO,SWITCK DE COMUNICAÇÃO,BAIXA ISOLACAO,FALTA FIXACAO

,TAG,Horário do Alarme,Estação,Porta,Alarme,Horário da Normalizacao,Tempo de Normalização
0,PSD_FAL_FAL2_PDM09_OBS,2026-05-12 08:16:52.657,FAL,9.0,OBS,2026-05-12 08:16:53.670,"0 dias, 00:00:01"
1,PSD_LUZ_LUZ1_PDM08_OBS,2026-05-12 08:15:09.913,LUZ,8.0,OBS,2026-05-12 08:15:10.917,"0 dias, 00:00:01"
2,PSD_FAL_FAL1_PDM15_OBS,2026-05-12 08:14:06.657,FAL,15.0,OBS,2026-05-12 08:14:07.670,"0 dias, 00:00:01"
3,PSD_LUZ_LUZ1_PDM19_OBS,2026-05-12 08:09:31.930,LUZ,19.0,OBS,2026-05-12 08:09:32.917,"0 dias, 00:00:01"
4,PSD_FRE_FRE1_PDM14_OBS,2026-05-12 08:05:05.830,FRE,14.0,OBS,2026-05-12 08:05:14.847,"0 dias, 00:00:09"

In [69]:
print("Alarmes:")
print(alarmes.isnull().sum())

print("\nCorretiva emergencial:")
print(correcao_emergencial.isnull().sum())

print("\nCorretiva programada:")
print(correcao_programada.isnull().sum())

Alarmes:
TAG                            1
Horário do Alarme          37252
Estação                        3
Porta                          3
Alarme                         3
Horário da Normalizacao        3
Tempo de Normalização          3
dtype: int64

Corretiva emergencial:
Local de Instalação         0
Início avaria               0
Hora início avaria          0
Fim da avaria             326
Hora do fim da avaria       0
Sintoma                     0
Objeto                    982
Defeito                   986
Causa                    1045
dtype: int64

Corretiva programada:
Local de Instalação       0
Início avaria             0
Hora início avaria        0
Fim da avaria            39
Hora do fim da avaria     0
Sintoma                   0
Objeto                   39
Defeito                  39
Causa                    42
dtype: int64

In [70]:
import numpy as np
alarmes_trat = alarmes.copy()

# Estação
alarmes_trat["estacao_key"] = (
    alarmes_trat["Estação"]
    .astype("string")
    .str.strip()
    .str.upper()
)

# Porta
alarmes_trat["porta_key"] = pd.to_numeric(
    alarmes_trat["Porta"],
    errors="coerce"
).astype("Int64")

# Extrair plataforma da TAG
# Exemplo: PSD_FAL_FAL2_PDM09_OBS
plataforma = alarmes_trat["TAG"].astype(str).str.extract(
    r"(?:^|_)([A-Z]{3})([12])_PDM(\d{2})(?:_|$)"
)

alarmes_trat["plataforma_key"] = pd.to_numeric(
    plataforma[1],
    errors="coerce"
).astype("Int64")

In [71]:
alarmes_trat["inicio_alarme"] = pd.to_datetime(
    alarmes_trat["Horário do Alarme"],
    errors="coerce"
)

alarmes_trat["fim_alarme"] = pd.to_datetime(
    alarmes_trat["Horário da Normalizacao"],
    errors="coerce"
)

In [72]:
alarmes_trat["tempo_normalizacao"] = (
    alarmes_trat["fim_alarme"]
    - alarmes_trat["inicio_alarme"]
)

alarmes_trat["tempo_normalizacao_min"] = (
    alarmes_trat["tempo_normalizacao"]
    .dt.total_seconds() / 60
)

In [73]:
display(
    alarmes_trat[
        [
            "TAG",
            "estacao_key",
            "plataforma_key",
            "porta_key",
            "inicio_alarme",
            "fim_alarme",
            "tempo_normalizacao_min"
        ]
    ].head(10)
)

,TAG,estacao_key,plataforma_key,porta_key,inicio_alarme,fim_alarme,tempo_normalizacao_min
0,PSD_FAL_FAL2_PDM09_OBS,FAL,2,9,2026-05-12 08:16:52.657,2026-05-12 08:16:53.670,0.016883
1,PSD_LUZ_LUZ1_PDM08_OBS,LUZ,1,8,2026-05-12 08:15:09.913,2026-05-12 08:15:10.917,0.016733
2,PSD_FAL_FAL1_PDM15_OBS,FAL,1,15,2026-05-12 08:14:06.657,2026-05-12 08:14:07.670,0.016883
3,PSD_LUZ_LUZ1_PDM19_OBS,LUZ,1,19,2026-05-12 08:09:31.930,2026-05-12 08:09:32.917,0.016450
4,PSD_FRE_FRE1_PDM14_OBS,FRE,1,14,2026-05-12 08:05:05.830,2026-05-12 08:05:14.847,0.150283
5,PSD_FRE_FRE1_PDM14_OBS,FRE,1,14,2026-05-12 08:05:02.847,2026-05-12 08:05:03.847,0.016667
6,PSD_LUZ_LUZ1_PDM15_OBS,LUZ,1,15,2026-05-12 07:52:33.930,2026-05-12 07:52:34.930,0.016667
7,PSD_HIG_HIG1_PDM16_OBS,HIG,1,16,2026-05-12 07:52:23.820,2026-05-12 07:52:24.820,0.016667
8,PSD_FAL_FAL1_PDM14_OBS,FAL,1,14,2026-05-12 07:50:21.703,2026-05-12 07:50:22.670,0.016117
9,PSD_LUZ_LUZ1_PDM08_OBS,LUZ,1,8,2026-05-12 07:33:46.900,2026-05-12 07:33:47.900,0.016667

In [74]:
programada_trat = correcao_programada.copy()

In [75]:
# Extrair estação do Local de Instalação
programada_trat["estacao_key"] = (
    programada_trat["Local de Instalação"]
    .astype(str)
    .str.extract(r"PSD-([A-Z]{3})", expand=False)
)

# Extrair plataforma
programada_trat["plataforma_key"] = pd.to_numeric(
    programada_trat["Local de Instalação"]
    .astype(str)
    .str.extract(r"PLT([12])", expand=False),
    errors="coerce"
).astype("Int64")

# Extrair porta
programada_trat["porta_key"] = pd.to_numeric(
    programada_trat["Local de Instalação"]
    .astype(str)
    .str.extract(r"PP(\d{2})PDM", expand=False),
    errors="coerce"
).astype("Int64")

In [76]:
data_inicio = pd.to_datetime(
    programada_trat["Início avaria"],
    dayfirst=True,
    errors="coerce"
)

hora_inicio = pd.to_timedelta(
    programada_trat["Hora início avaria"].astype(str),
    errors="coerce"
)

programada_trat["inicio_avaria_dt"] = (
    data_inicio.dt.normalize()
    + hora_inicio
)

In [77]:
data_fim = pd.to_datetime(
    programada_trat["Fim da avaria"],
    dayfirst=True,
    errors="coerce"
)

hora_fim = pd.to_timedelta(
    programada_trat["Hora do fim da avaria"].astype(str),
    errors="coerce"
)

programada_trat["fim_avaria_dt"] = (
    data_fim.dt.normalize()
    + hora_fim
)

In [78]:
programada_trat["duracao_avaria"] = (
    programada_trat["fim_avaria_dt"]
    - programada_trat["inicio_avaria_dt"]
)

programada_trat["duracao_avaria_min"] = (
    programada_trat["duracao_avaria"]
    .dt.total_seconds() / 60
)

In [79]:
display(
    programada_trat[
        [
            "Local de Instalação",
            "estacao_key",
            "plataforma_key",
            "porta_key",
            "inicio_avaria_dt",
            "fim_avaria_dt",
            "duracao_avaria_min",
            "Sintoma",
            "Objeto",
            "Defeito",
            "Causa"
        ]
    ].head(10)
)

,Local de Instalação,estacao_key,plataforma_key,porta_key,inicio_avaria_dt,fim_avaria_dt,duracao_avaria_min,Sintoma,Objeto,Defeito,Causa
0,SP04-6-PSD-BUT,BUT,<NA>,<NA>,2026-01-25 08:20:00,2026-01-25 09:30:00,70.000000,PDM NÃO ABRE,"ESTRUTURA, ACABAMENTO, E ACESSÓRIOS DO P",PORTA DESAJUSTADA,FALTA FIXACAO
1,SP04-6-PSD-BUT-P1S1,BUT,<NA>,<NA>,2025-05-30 09:30:00,2025-06-01 04:00:00,2550.000000,MAU CONTATO,SWITCK DE COMUNICAÇÃO,SEM CONEXAO ELETRICA,ERRO DE SOFTWARE
2,SP04-6-PSD-BUT-P2S1-PSSE2,BUT,<NA>,<NA>,2025-06-19 02:00:00,2025-06-19 04:30:00,150.000000,FACHADA PSD SEM ALIMENTAÇÃO,DISPOSITIVO DE PROTECAO,CONVERSOR DE TENSAO AVARIADO,OPERACAO INDEVIDA
3,SP04-6-PSD-BUT-P2S1-PSSE2,BUT,<NA>,<NA>,2025-09-30 09:00:00,2025-09-30 12:00:00,180.000000,ESTRUTURA DANIFICADA,MULTIMEDIDOR,VIDRO QUEBRADO,DESGASTE
4,SP04-6-PSD-BUT-PLT1,BUT,1,<NA>,2023-07-21 14:00:00,2023-07-27 13:50:56,8630.933333,SERVIDOR SEM COMUNICACAO,SWITCK DE COMUNICAÇÃO,BAIXA ISOLACAO,FALTA FIXACAO
5,SP04-6-PSD-BUT-PLT1,BUT,1,<NA>,2024-04-25 08:00:00,2024-04-25 15:30:00,450.000000,PDM NÃO FECHOU,ESTRUTURA E ACABAMENTOS PDM,ATUADOR DA TRAVA DE PDM DESAJUSTADO,ERRO DE COMUNICAÇÃO
6,SP04-6-PSD-BUT-PLT1-PFP1,BUT,1,<NA>,2023-04-30 17:40:50,2023-05-01 04:06:00,625.166667,ESTRUTURA DANIFICADA,PORTA FINAL PLATAF PFP,IHM TRAVADA,VANDALISMO
7,SP04-6-PSD-BUT-PLT1-PP05PDM,BUT,1,5,2025-02-20 04:00:33,2025-02-24 15:20:00,6439.450000,LAMPADA(S) NAO ACENDE(M),SPEAKER PDM,MCP TRAVADO,OPERACAO INDEVIDA
8,SP04-6-PSD-BUT-PLT1-PP06PSE,BUT,1,<NA>,2024-12-04 03:13:00,2025-08-02 01:30:00,346937.000000,PDM PESADA,LINGUETA DA TRAVA ESQUERDA PSE PSD,PORTA DESAJUSTADA,VIBRACAO
9,SP04-6-PSD-BUT-PLT1-PP10PDM,BUT,1,10,2023-12-09 15:00:00,2024-01-29 11:00:00,73200.000000,PORTA COM RUÍDO ANORMAL,ALTO-FALANTE (SPEAKER),MCP AVARIADO,ERRO DE COMUNICAÇÃO

In [80]:
emergencial_trat = correcao_emergencial.copy()

local = emergencial_trat["Local de Instalação"].astype(str)

In [81]:
emergencial_trat["estacao_key"] = local.str.extract(
    r"PSD-([A-Z]{3})",
    expand=False
)

In [82]:
emergencial_trat["plataforma_key"] = pd.to_numeric(
    local.str.extract(
        r"PLT([12])",
        expand=False
    ),
    errors="coerce"
).astype("Int64")

In [83]:
emergencial_trat["porta_key"] = pd.to_numeric(
    local.str.extract(
        r"PP(\d{2})PDM",
        expand=False
    ),
    errors="coerce"
).astype("Int64")

In [84]:
data_inicio = pd.to_datetime(
    emergencial_trat["Início avaria"],
    dayfirst=True,
    errors="coerce"
)

hora_inicio = pd.to_timedelta(
    emergencial_trat["Hora início avaria"].astype(str),
    errors="coerce"
)

emergencial_trat["inicio_avaria_dt"] = (
    data_inicio.dt.normalize()
    + hora_inicio
)

In [85]:
data_fim = pd.to_datetime(
    emergencial_trat["Fim da avaria"],
    dayfirst=True,
    errors="coerce"
)

hora_fim = pd.to_timedelta(
    emergencial_trat["Hora do fim da avaria"].astype(str),
    errors="coerce"
)

emergencial_trat["fim_avaria_dt"] = (
    data_fim.dt.normalize()
    + hora_fim
)

In [86]:
emergencial_trat["duracao_avaria"] = (
    emergencial_trat["fim_avaria_dt"]
    - emergencial_trat["inicio_avaria_dt"]
)

emergencial_trat["duracao_avaria_min"] = (
    emergencial_trat["duracao_avaria"]
    .dt.total_seconds() / 60
)

In [87]:
display(
    emergencial_trat[
        [
            "Local de Instalação",
            "estacao_key",
            "plataforma_key",
            "porta_key",
            "inicio_avaria_dt",
            "fim_avaria_dt",
            "duracao_avaria_min"
        ]
    ].head(10)
)

,Local de Instalação,estacao_key,plataforma_key,porta_key,inicio_avaria_dt,fim_avaria_dt,duracao_avaria_min
0,SP04-6-PSD-BUT,BUT,<NA>,<NA>,2025-11-14 06:35:28,NaT,NaN
1,SP04-6-PSD-BUT,BUT,<NA>,<NA>,2026-02-27 07:33:00,2026-02-27 12:00:00,267.000000
2,SP04-6-PSD-BUT-P1S1,BUT,<NA>,<NA>,2024-04-18 06:00:00,2024-04-18 07:30:00,90.000000
3,SP04-6-PSD-BUT-P1S1,BUT,<NA>,<NA>,2025-07-07 18:38:00,2025-07-08 03:00:00,502.000000
4,SP04-6-PSD-BUT-P1S1-PSSE1,BUT,<NA>,<NA>,2025-05-28 09:10:00,2025-05-28 10:00:00,50.000000
5,SP04-6-PSD-BUT-P1S1-PSSE1,BUT,<NA>,<NA>,2025-06-18 17:00:38,2025-06-19 04:00:00,659.366667
6,SP04-6-PSD-BUT-P2S1,BUT,<NA>,<NA>,2025-11-24 16:20:15,2025-11-24 17:30:00,69.750000
7,SP04-6-PSD-BUT-P2S1-PSSE2,BUT,<NA>,<NA>,2025-07-18 07:33:00,2025-07-19 05:18:29,1305.483333
8,SP04-6-PSD-BUT-PLT1,BUT,1,<NA>,2023-04-23 19:15:00,2023-04-23 20:20:00,65.000000
9,SP04-6-PSD-BUT-PLT1,BUT,1,<NA>,2023-09-06 16:16:00,2023-09-06 16:56:00,40.000000

In [88]:
# Extrair informações escondidas na TAG

alarmes_trat["estacao_tag"] = alarmes_trat["TAG"].str.extract(
    r"^PSD_([A-Z]{3})_",
    expand=False
)

alarmes_trat["plataforma_tag"] = pd.to_numeric(
    alarmes_trat["TAG"].str.extract(
        r"_[A-Z]{3}([12])_PDM",
        expand=False
    ),
    errors="coerce"
).astype("Int64")

alarmes_trat["porta_tag"] = pd.to_numeric(
    alarmes_trat["TAG"].str.extract(
        r"PDM(\d{2})",
        expand=False
    ),
    errors="coerce"
).astype("Int64")

alarmes_trat["alarme_tag"] = alarmes_trat["TAG"].str.extract(
    r"_([^_]+)$",
    expand=False
)

In [89]:
alarmes_trat["Estação"] = alarmes_trat["Estação"].fillna(
    alarmes_trat["estacao_tag"]
)

alarmes_trat["Porta"] = alarmes_trat["Porta"].fillna(
    alarmes_trat["porta_tag"]
)

alarmes_trat["Alarme"] = alarmes_trat["Alarme"].fillna(
    alarmes_trat["alarme_tag"]
)

In [90]:
alarmes_trat["Plataforma"] = alarmes_trat["plataforma_tag"]

In [91]:
alarmes_trat["inicio_alarme"] = pd.to_datetime(
    alarmes_trat["Horário do Alarme"],
    errors="coerce"
)

alarmes_trat["fim_alarme"] = pd.to_datetime(
    alarmes_trat["Horário da Normalizacao"],
    errors="coerce"
)

alarmes_trat["tempo_normalizacao_calc"] = (
    alarmes_trat["fim_alarme"]
    - alarmes_trat["inicio_alarme"]
)

alarmes_trat["tempo_normalizacao_min"] = (
    alarmes_trat["tempo_normalizacao_calc"]
    .dt.total_seconds() / 60
)

In [92]:
emergencial_trat["estacao_key"] = (
    emergencial_trat["Local de Instalação"]
    .str.extract(r"PSD-([A-Z]{3})", expand=False)
)

emergencial_trat["plataforma_key"] = pd.to_numeric(
    emergencial_trat["Local de Instalação"]
    .str.extract(r"PLT([12])", expand=False),
    errors="coerce"
).astype("Int64")

emergencial_trat["porta_key"] = pd.to_numeric(
    emergencial_trat["Local de Instalação"]
    .str.extract(r"PP(\d{2})PDM", expand=False),
    errors="coerce"
).astype("Int64")

In [93]:
programada_trat["estacao_key"] = (
    programada_trat["Local de Instalação"]
    .str.extract(r"PSD-([A-Z]{3})", expand=False)
)

programada_trat["plataforma_key"] = pd.to_numeric(
    programada_trat["Local de Instalação"]
    .str.extract(r"PLT([12])", expand=False),
    errors="coerce"
).astype("Int64")

programada_trat["porta_key"] = pd.to_numeric(
    programada_trat["Local de Instalação"]
    .str.extract(r"PP(\d{2})PDM", expand=False),
    errors="coerce"
).astype("Int64")

In [94]:
print(emergencial_trat.columns.tolist())

['Local de Instalação', 'Início avaria', 'Hora início avaria', 'Fim da avaria', 'Hora do fim da avaria', 'Sintoma', 'Objeto', 'Defeito', 'Causa', 'estacao_key', 'plataforma_key', 'porta_key', 'inicio_avaria_dt', 'fim_avaria_dt', 'duracao_avaria', 'duracao_avaria_min']

In [95]:
print(programada_trat.columns.tolist())

['Local de Instalação', 'Início avaria', 'Hora início avaria', 'Fim da avaria', 'Hora do fim da avaria', 'Sintoma', 'Objeto', 'Defeito', 'Causa', 'estacao_key', 'plataforma_key', 'porta_key', 'inicio_avaria_dt', 'fim_avaria_dt', 'duracao_avaria', 'duracao_avaria_min']

In [96]:
fim_nulo_emergencial = (
    emergencial_trat["Fim da avaria"].isna()
    & emergencial_trat["Início avaria"].notna()
    & emergencial_trat["Hora início avaria"].notna()
    & emergencial_trat["Hora do fim da avaria"].notna()
)

print("Possíveis datas de fim recuperáveis:", fim_nulo_emergencial.sum())

Possíveis datas de fim recuperáveis: 326

In [97]:
data_inicio = pd.to_datetime(
    emergencial_trat["Início avaria"],
    dayfirst=True,
    errors="coerce"
)

hora_inicio = pd.to_timedelta(
    emergencial_trat["Hora início avaria"].astype(str),
    errors="coerce"
)

hora_fim = pd.to_timedelta(
    emergencial_trat["Hora do fim da avaria"].astype(str),
    errors="coerce"
)

In [98]:
data_fim_estimado = data_inicio.dt.normalize().copy()

# Se o horário final for menor que o inicial,
# significa que provavelmente virou o dia
virou_dia = hora_fim < hora_inicio

data_fim_estimado.loc[virou_dia] = (
    data_fim_estimado.loc[virou_dia]
    + pd.Timedelta(days=1)
)

In [99]:
# Datas e horários convertidos
data_inicio = pd.to_datetime(
    emergencial_trat["Início avaria"],
    dayfirst=True,
    errors="coerce"
)

hora_inicio = pd.to_timedelta(
    emergencial_trat["Hora início avaria"].astype(str),
    errors="coerce"
)

data_fim = pd.to_datetime(
    emergencial_trat["Fim da avaria"],
    dayfirst=True,
    errors="coerce"
)

hora_fim = pd.to_timedelta(
    emergencial_trat["Hora do fim da avaria"].astype(str),
    errors="coerce"
)

# Datetime de início
emergencial_trat["inicio_avaria_dt"] = (
    data_inicio.dt.normalize() + hora_inicio
)

# Datetime de fim quando a data original existe
emergencial_trat["fim_avaria_dt"] = (
    data_fim.dt.normalize() + hora_fim
)

In [100]:
fim_nulo_emergencial = (
    data_fim.isna()
    & data_inicio.notna()
    & hora_inicio.notna()
    & hora_fim.notna()
)

print("Possíveis casos para imputação:", fim_nulo_emergencial.sum())

Possíveis casos para imputação: 326

In [101]:
fim_estimado = (
    data_inicio.dt.normalize()
    + hora_fim
)

# Se o horário final for menor que o horário inicial,
# assumimos que terminou no dia seguinte
virou_dia = (
    fim_nulo_emergencial
    & (hora_fim < hora_inicio)
)

fim_estimado.loc[virou_dia] = (
    fim_estimado.loc[virou_dia]
    + pd.Timedelta(days=1)
)

In [102]:
emergencial_trat["fim_avaria_imputado"] = False

emergencial_trat.loc[
    fim_nulo_emergencial,
    "fim_avaria_dt"
] = fim_estimado.loc[fim_nulo_emergencial]

emergencial_trat.loc[
    fim_nulo_emergencial,
    "fim_avaria_imputado"
] = True

In [103]:
display(
    emergencial_trat[
        emergencial_trat["fim_avaria_imputado"]
    ][
        [
            "Início avaria",
            "Hora início avaria",
            "Fim da avaria",
            "Hora do fim da avaria",
            "inicio_avaria_dt",
            "fim_avaria_dt",
            "duracao_avaria_min"
        ]
    ].head(20)
)

,Início avaria,Hora início avaria,Fim da avaria,Hora do fim da avaria,inicio_avaria_dt,fim_avaria_dt,duracao_avaria_min
0,14/11/2025,06:35:28,NaN,00:00:00,2025-11-14 06:35:28,2025-11-15,NaN
19,16/09/2025,18:44:00,NaN,00:00:00,2025-09-16 18:44:00,2025-09-17,NaN
49,14/10/2025,20:40:00,NaN,00:00:00,2025-10-14 20:40:00,2025-10-15,NaN
50,14/10/2025,23:05:00,NaN,00:00:00,2025-10-14 23:05:00,2025-10-15,NaN
67,08/02/2024,16:42:00,NaN,00:00:00,2024-02-08 16:42:00,2024-02-09,NaN
255,08/07/2024,15:54:00,NaN,00:00:00,2024-07-08 15:54:00,2024-07-09,NaN
270,08/08/2023,05:06:00,NaN,00:00:00,2023-08-08 05:06:00,2023-08-09,NaN
414,09/11/2024,06:36:00,NaN,00:00:00,2024-11-09 06:36:00,2024-11-10,NaN
696,03/03/2026,02:40:00,NaN,00:00:00,2026-03-03 02:40:00,2026-03-04,NaN
806,12/03/2024,19:13:00,NaN,00:00:00,2024-03-12 19:13:00,2024-03-13,NaN
845,15/06/2023,08:36:58,NaN,00:00:00,2023-06-15 08:36:58,2023-06-16,NaN
858,13/06/2023,12:47:30,NaN,00:00:00,2023-06-13 12:47:30,2023-06-14,NaN
893,08/07/2023,15:54:02,NaN,00:00:00,2023-07-08 15:54:02,2023-07-09,NaN
909,15/06/2023,09:41:28,NaN,00:00:00,2023-06-15 09:41:28,2023-06-16,NaN
933,15/06/2023,08:36:58,NaN,00:00:00,2023-06-15 08:36:58,2023-06-16,NaN
965,29/12/2023,09:51:35,NaN,00:00:00,2023-12-29 09:51:35,2023-12-30,NaN
1032,12/12/2023,06:10:00,NaN,00:00:00,2023-12-12 06:10:00,2023-12-13,NaN
1047,07/11/2024,23:11:02,NaN,00:00:00,2024-11-07 23:11:02,2024-11-08,NaN
1119,15/06/2023,08:36:58,NaN,00:00:00,2023-06-15 08:36:58,2023-06-16,NaN
1130,29/05/2023,06:20:40,NaN,00:00:00,2023-05-29 06:20:40,2023-05-30,NaN

In [104]:
mascara_fim_invalido = (
    emergencial_trat["Fim da avaria"].isna()
    & (
        pd.to_timedelta(
            emergencial_trat["Hora do fim da avaria"].astype(str),
            errors="coerce"
        ) == pd.Timedelta(0)
    )
)

print("Registros com fim inválido:", mascara_fim_invalido.sum())

Registros com fim inválido: 326

In [105]:
emergencial_trat.loc[
    mascara_fim_invalido,
    "fim_avaria_dt"
] = pd.NaT

In [106]:
emergencial_trat["duracao_avaria"] = (
    emergencial_trat["fim_avaria_dt"]
    - emergencial_trat["inicio_avaria_dt"]
)

emergencial_trat["duracao_avaria_min"] = (
    emergencial_trat["duracao_avaria"]
    .dt.total_seconds() / 60
)

In [107]:
print("Antes:", emergencial_trat.shape)

print(
    "Linhas com duração NaN:",
    emergencial_trat["duracao_avaria_min"].isna().sum()
)

Antes: (10647, 17)
Linhas com duração NaN: 326

In [108]:
emergencial_trat = emergencial_trat.dropna(
    subset=["duracao_avaria_min"]
)

In [109]:
print("Depois:", emergencial_trat.shape)
print(
    emergencial_trat["duracao_avaria_min"].isna().sum()
)

Depois: (10321, 17)
0

In [110]:
programada_trat = programada_trat.dropna(
    subset=["duracao_avaria_min"]
)

In [111]:
print(alarmes_trat[
    [
        "Horário do Alarme",
        "Horário da Normalizacao",
        "Tempo de Normalização"
    ]
].dtypes)

display(
    alarmes_trat[
        [
            "Horário do Alarme",
            "Horário da Normalizacao",
            "Tempo de Normalização"
        ]
    ].head(20)
)

print("\nValores nulos:")
print(
    alarmes_trat[
        [
            "Horário do Alarme",
            "Horário da Normalizacao",
            "Tempo de Normalização"
        ]
    ].isna().sum()
)

Horário do Alarme          datetime64[us]
Horário da Normalizacao    datetime64[us]
Tempo de Normalização                 str
dtype: object

         Horário do Alarme Horário da Normalizacao Tempo de Normalização
0  2026-05-12 08:16:52.657 2026-05-12 08:16:53.670      0 dias, 00:00:01
1  2026-05-12 08:15:09.913 2026-05-12 08:15:10.917      0 dias, 00:00:01
2  2026-05-12 08:14:06.657 2026-05-12 08:14:07.670      0 dias, 00:00:01
3  2026-05-12 08:09:31.930 2026-05-12 08:09:32.917      0 dias, 00:00:01
4  2026-05-12 08:05:05.830 2026-05-12 08:05:14.847      0 dias, 00:00:09
5  2026-05-12 08:05:02.847 2026-05-12 08:05:03.847      0 dias, 00:00:01
6  2026-05-12 07:52:33.930 2026-05-12 07:52:34.930      0 dias, 00:00:01
7  2026-05-12 07:52:23.820 2026-05-12 07:52:24.820      0 dias, 00:00:01
8  2026-05-12 07:50:21.703 2026-05-12 07:50:22.670      0 dias, 00:00:01
9  2026-05-12 07:33:46.900 2026-05-12 07:33:47.900      0 dias, 00:00:01
10 2026-05-12 07:31:42.900 2026-05-12 07:31:44.900      0 dias, 00:00:02
11 2026-05-12 07:31:39.900 2026-05-12 07:31:40.900      0 dias, 00:00:01
12 2026-05-12 07:31:39.900 2026-05-12 07:31:40.900      0 dias, 00:00:01
13 2026-05-12 06:40:58.853 2026-05-12 06:40:59.837      0 dias, 00:00:01
14 2026-05-12 06:32:30.837 2026-05-12 06:32:41.853      0 dias, 00:00:11
15 2026-05-12 06:23:14.837 2026-05-12 06:23:15.837      0 dias, 00:00:01
16 2026-05-12 06:20:01.837 2026-05-12 06:20:02.837      0 dias, 00:00:01
17 2026-05-12 05:52:14.727 2026-05-12 05:52:21.727      0 dias, 00:00:07
18 2026-05-12 05:48:17.740 2026-05-12 05:48:18.787      0 dias, 00:00:01
19 2026-05-12 05:48:10.723 2026-05-12 05:48:11.740      0 dias, 00:00:01

Valores nulos:
Horário do Alarme          37252
Horário da Normalizacao        3
Tempo de Normalização          3
dtype: int64

In [112]:
tempo_original = pd.to_timedelta(
    alarmes_trat["Tempo de Normalização"]
    .str.replace(
        r"(\d+)\s+dias?,\s*",
        r"\1 days ",
        regex=True
    ),
    errors="coerce"
)

tempo_calculado = (
    alarmes_trat["Horário da Normalizacao"]
    - alarmes_trat["Horário do Alarme"]
)

diferenca_segundos = (
    tempo_calculado.dt.total_seconds()
    - tempo_original.dt.total_seconds()
).abs()

validos = (
    tempo_calculado.notna()
    & tempo_original.notna()
)

print("Registros comparáveis:", validos.sum())

print(
    "Diferença média:",
    diferenca_segundos[validos].mean(),
    "segundos"
)

print(
    "Diferença máxima:",
    diferenca_segundos[validos].max(),
    "segundos"
)

print(
    "Até 1 segundo de diferença:",
    (diferenca_segundos[validos] <= 1).mean() * 100,
    "%"
)

Registros comparáveis: 112751
Diferença média: 5.414053143652222 segundos
Diferença máxima: 70923.67300000001 segundos
Até 1 segundo de diferença: 99.5192947290933 %

In [113]:
print(
    "Casos com diferença > 1 segundo:",
    (diferenca_segundos[validos] > 1).sum()
)

print(
    "Casos com diferença > 5 segundos:",
    (diferenca_segundos[validos] > 5).sum()
)

print(
    "Casos com diferença > 60 segundos:",
    (diferenca_segundos[validos] > 60).sum()
)

print("\nPercentis da diferença:")

print(
    diferenca_segundos[validos].quantile(
        [0.50, 0.90, 0.95, 0.99, 0.995, 0.999, 1]
    )
)

Casos com diferença > 1 segundo: 542
Casos com diferença > 5 segundos: 301
Casos com diferença > 60 segundos: 30

Percentis da diferença:
0.500        0.157
0.900        0.630
0.950        0.743
0.990        0.937
0.995        0.987
0.999        8.000
1.000    70923.673
dtype: float64

In [114]:
outliers_tempo = alarmes_trat[
    validos & (diferenca_segundos > 1)
].copy()

outliers_tempo["tempo_original_calc"] = tempo_original[
    validos & (diferenca_segundos > 1)
]

outliers_tempo["tempo_timestamp_calc"] = tempo_calculado[
    validos & (diferenca_segundos > 1)
]

outliers_tempo["diferenca_segundos"] = diferenca_segundos[
    validos & (diferenca_segundos > 1)
]

display(
    outliers_tempo[
        [
            "TAG",
            "Horário do Alarme",
            "Horário da Normalizacao",
            "Tempo de Normalização",
            "tempo_original_calc",
            "tempo_timestamp_calc",
            "diferenca_segundos"
        ]
    ].sort_values(
        "diferenca_segundos",
        ascending=False
    ).head(20)
)

,TAG,Horário do Alarme,Horário da Normalizacao,Tempo de Normalização,tempo_original_calc,tempo_timestamp_calc,diferenca_segundos
21677,PSD_LUZ_LUZ1_PDM07_OBS,2026-01-16 06:54:19.500,2026-01-16 16:45:21.827,"1 dias, 05:33:06",1 days 05:33:06,0 days 09:51:02.327000,70923.673
21461,PSD_FRA_FRA2_PDM10_OBS,2026-01-17 05:52:28.140,2026-01-17 15:23:14.327,"1 dias, 04:32:18",1 days 04:32:18,0 days 09:30:46.187000,68491.813
21688,PSD_LUZ_LUZ1_PDM18_OBS,2026-01-16 07:29:28.500,2026-01-16 16:45:21.827,"1 dias, 03:47:39",1 days 03:47:39,0 days 09:15:53.327000,66705.673
21686,PSD_LUZ_LUZ1_PDM16_OBS,2026-01-16 07:27:23.500,2026-01-16 16:45:21.827,"0 dias, 18:35:56",0 days 18:35:56,0 days 09:17:58.327000,33477.673
21690,PSD_LUZ_LUZ1_PDM20_OBS,2026-01-16 07:40:29.500,2026-01-16 16:45:21.827,"0 dias, 18:09:44",0 days 18:09:44,0 days 09:04:52.327000,32691.673
21689,PSD_LUZ_LUZ1_PDM19_OBS,2026-01-16 07:47:04.500,2026-01-16 16:45:21.827,"0 dias, 17:56:34",0 days 17:56:34,0 days 08:58:17.327000,32296.673
21685,PSD_LUZ_LUZ1_PDM15_OBS,2026-01-16 07:47:04.500,2026-01-16 16:45:21.827,"0 dias, 17:56:34",0 days 17:56:34,0 days 08:58:17.327000,32296.673
21687,PSD_LUZ_LUZ1_PDM17_OBS,2026-01-16 07:53:35.500,2026-01-16 16:45:21.827,"0 dias, 17:43:32",0 days 17:43:32,0 days 08:51:46.327000,31905.673
21678,PSD_LUZ_LUZ1_PDM08_OBS,2026-01-16 12:24:39.577,2026-01-16 16:45:21.827,"0 dias, 13:02:06",0 days 13:02:06,0 days 04:20:42.250000,31283.750
21679,PSD_LUZ_LUZ1_PDM09_OBS,2026-01-16 12:28:35.593,2026-01-16 16:45:21.827,"0 dias, 12:50:18",0 days 12:50:18,0 days 04:16:46.234000,30811.766
40123,PSD_BUT_BUT1_PDM16_OBS,2025-10-15 05:30:15.620,2025-10-15 13:47:34.243,"0 dias, 16:34:38",0 days 16:34:38,0 days 08:17:18.623000,29839.377
40214,PSD_P_BUT1_MDU16_STS,2025-10-15 05:30:15.620,2025-10-15 13:47:34.243,"0 dias, 16:34:38",0 days 16:34:38,0 days 08:17:18.623000,29839.377
21457,PSD_FRA_FRA2_PDM06_OBS,2026-01-17 12:03:42.203,2026-01-17 15:23:14.327,"0 dias, 09:58:36",0 days 09:58:36,0 days 03:19:32.124000,23943.876
21676,PSD_LUZ_LUZ1_PDM06_OBS,2026-01-16 10:37:02.547,2026-01-16 16:45:21.827,"0 dias, 12:16:38",0 days 12:16:38,0 days 06:08:19.280000,22098.720
21433,PSD_FRA_FRA1_PDM06_OBS,2026-01-17 12:43:58.233,2026-01-17 15:23:14.327,"0 dias, 07:57:48",0 days 07:57:48,0 days 02:39:16.094000,19111.906
40156,PSD_BUT_BUT2_PDM09_OBS,2025-10-15 11:45:57.713,2025-10-15 13:47:34.243,"0 dias, 04:03:14",0 days 04:03:14,0 days 02:01:36.530000,7297.470
41411,PSD_HIG_HIG2_PDM15_OBS,2025-10-13 00:10:49.370,2025-10-13 02:11:20.957,"0 dias, 04:01:02",0 days 04:01:02,0 days 02:00:31.587000,7230.413
41786,PSD_HIG_HIG2_PDM15_OBS,2025-10-13 00:10:49.370,2025-10-13 01:14:20.877,"0 dias, 02:07:02",0 days 02:07:02,0 days 01:03:31.507000,3810.493
41879,PSD_HIG_HIG2_PDM15_OBS,2025-10-13 00:10:49.370,2025-10-13 01:12:22.050,"0 dias, 02:03:06",0 days 02:03:06,0 days 01:01:32.680000,3693.320
21515,PSD_P_BUT1_MDU21_STS,2026-01-17 04:17:14.007,2026-01-17 04:24:24.007,"0 dias, 00:21:30",0 days 00:21:30,0 days 00:07:10,860.000

In [115]:
alarmes_analise = alarmes_trat[
    alarmes_trat["Horário do Alarme"].notna()
    & alarmes_trat["Horário da Normalizacao"].notna()
].copy()

In [116]:
print("Base original:", len(alarmes_trat))
print("Base válida para análise temporal:", len(alarmes_analise))
print("Registros retirados:", len(alarmes_trat) - len(alarmes_analise))

Base original: 150003
Base válida para análise temporal: 112751
Registros retirados: 37252

In [117]:
alarmes_analise["tempo_normalizacao"] = (
    alarmes_analise["Horário da Normalizacao"]
    - alarmes_analise["Horário do Alarme"]
)

alarmes_analise["tempo_normalizacao_seg"] = (
    alarmes_analise["tempo_normalizacao"]
    .dt.total_seconds()
)

alarmes_analise["tempo_normalizacao_min"] = (
    alarmes_analise["tempo_normalizacao_seg"] / 60
)

In [118]:
display(
    alarmes_analise[
        [
            "TAG",
            "Horário do Alarme",
            "Horário da Normalizacao",
            "tempo_normalizacao_seg",
            "tempo_normalizacao_min"
        ]
    ].head(10)
)

,TAG,Horário do Alarme,Horário da Normalizacao,tempo_normalizacao_seg,tempo_normalizacao_min
0,PSD_FAL_FAL2_PDM09_OBS,2026-05-12 08:16:52.657,2026-05-12 08:16:53.670,1.013,0.016883
1,PSD_LUZ_LUZ1_PDM08_OBS,2026-05-12 08:15:09.913,2026-05-12 08:15:10.917,1.004,0.016733
2,PSD_FAL_FAL1_PDM15_OBS,2026-05-12 08:14:06.657,2026-05-12 08:14:07.670,1.013,0.016883
3,PSD_LUZ_LUZ1_PDM19_OBS,2026-05-12 08:09:31.930,2026-05-12 08:09:32.917,0.987,0.016450
4,PSD_FRE_FRE1_PDM14_OBS,2026-05-12 08:05:05.830,2026-05-12 08:05:14.847,9.017,0.150283
5,PSD_FRE_FRE1_PDM14_OBS,2026-05-12 08:05:02.847,2026-05-12 08:05:03.847,1.000,0.016667
6,PSD_LUZ_LUZ1_PDM15_OBS,2026-05-12 07:52:33.930,2026-05-12 07:52:34.930,1.000,0.016667
7,PSD_HIG_HIG1_PDM16_OBS,2026-05-12 07:52:23.820,2026-05-12 07:52:24.820,1.000,0.016667
8,PSD_FAL_FAL1_PDM14_OBS,2026-05-12 07:50:21.703,2026-05-12 07:50:22.670,0.967,0.016117
9,PSD_LUZ_LUZ1_PDM08_OBS,2026-05-12 07:33:46.900,2026-05-12 07:33:47.900,1.000,0.016667

In [119]:
emergencial_trat["tipo_manutencao"] = "Emergencial"
programada_trat["tipo_manutencao"] = "Programada"

manutencoes = pd.concat(
    [
        emergencial_trat,
        programada_trat
    ],
    ignore_index=True
)

In [120]:
print("Emergenciais:", len(emergencial_trat))
print("Programadas:", len(programada_trat))
print("Total:", len(manutencoes))

print("\nTipos:")
print(manutencoes["tipo_manutencao"].value_counts())

Emergenciais: 10321
Programadas: 1124
Total: 11445

Tipos:
tipo_manutencao
Emergencial    10321
Programada      1124
Name: count, dtype: int64

In [121]:
display(
    manutencoes[
        [
            "estacao_key",
            "plataforma_key",
            "porta_key",
            "inicio_avaria_dt",
            "fim_avaria_dt",
            "duracao_avaria_min",
            "Sintoma",
            "Objeto",
            "Defeito",
            "Causa",
            "tipo_manutencao"
        ]
    ].head(10)
)

,estacao_key,plataforma_key,porta_key,inicio_avaria_dt,fim_avaria_dt,duracao_avaria_min,Sintoma,Objeto,Defeito,Causa,tipo_manutencao
0,BUT,<NA>,<NA>,2026-02-27 07:33:00,2026-02-27 12:00:00,267.000000,TODAS AS PDM DA FACHADA NÃO ABREM,CABEAMENTO,CONTROLADOR PCC COMUNICACAO,ERRO DE COMUNICAÇÃO,Emergencial
1,BUT,<NA>,<NA>,2024-04-18 06:00:00,2024-04-18 07:30:00,90.000000,PSD SERVER COM INDICAÇÃO DE FALHA NA PLA,RACK WCN,SENSOR DESTRAVADO AVARIADO,DESGASTE,Emergencial
2,BUT,<NA>,<NA>,2025-07-07 18:38:00,2025-07-08 03:00:00,502.000000,TODAS AS PDM DA FACHADA NÃO ABREM,CABO/CONECTORES,SWITCH TRAVADO,DESGASTE,Emergencial
3,BUT,<NA>,<NA>,2025-05-28 09:10:00,2025-05-28 10:00:00,50.000000,PDM NÃO ABRE,CABEAMENTO,BAIXA ISOLACAO,FALHA CBTC,Emergencial
4,BUT,<NA>,<NA>,2025-06-18 17:00:38,2025-06-19 04:00:00,659.366667,LAÇO DE PDM ABERTO,DISPOSITIVO DE PROTECAO,CONTATOR DE EQUALIZACAO OVPD AVARIADO,OPERACAO INDEVIDA,Emergencial
5,BUT,<NA>,<NA>,2025-11-24 16:20:15,2025-11-24 17:30:00,69.750000,LAÇO DE PDM ABERTO,CABEAMENTO,SEM CONEXAO ELETRICA,ERRO DE COMUNICAÇÃO,Emergencial
6,BUT,<NA>,<NA>,2025-07-18 07:33:00,2025-07-19 05:18:29,1305.483333,PSD SERVER COM INDICAÇÃO DE FALHA NA PLA,MODULO ANALISE ALIMENTAC REDUNDANTE,BAIXA ISOLACAO,DESGASTE,Emergencial
7,BUT,1,<NA>,2023-04-23 19:15:00,2023-04-23 20:20:00,65.000000,LAÇO DE PDM ABERTO SEM INDICACAO DO LOCA,PAINEL PSC-CP PCC,PERDA DE COMUNICACAO,ERRO DE COMUNICAÇÃO,Emergencial
8,BUT,1,<NA>,2023-09-06 16:16:00,2023-09-06 16:56:00,40.000000,LAÇO DE PDM ABERTO,TRAVA DA PORTA,ATUADOR DA TRAVA DE PDM DESAJUSTADO,VIBRACAO,Emergencial
9,BUT,1,<NA>,2023-09-26 04:25:00,2023-09-27 02:12:07,1307.116667,PDM NÃO FECHOU,SWITCH ETHERNET 8 PORTAS PCC PSD,PERDA DE COMUNICACAO,ERRO DE COMUNICAÇÃO,Emergencial

In [122]:
alarmes_match = alarmes_analise.dropna(
    subset=[
        "estacao_key",
        "plataforma_key",
        "porta_key",
        "Horário do Alarme"
    ]
).copy()

manutencoes_match = manutencoes.dropna(
    subset=[
        "estacao_key",
        "plataforma_key",
        "porta_key",
        "inicio_avaria_dt"
    ]
).copy()

In [123]:
alarmes_match["plataforma_key"] = (
    alarmes_match["plataforma_key"].astype("Int64")
)

alarmes_match["porta_key"] = (
    alarmes_match["porta_key"].astype("Int64")
)

manutencoes_match["plataforma_key"] = (
    manutencoes_match["plataforma_key"].astype("Int64")
)

manutencoes_match["porta_key"] = (
    manutencoes_match["porta_key"].astype("Int64")
)

In [124]:
manutencoes_match = manutencoes_match[
    [
        "estacao_key",
        "plataforma_key",
        "porta_key",
        "inicio_avaria_dt",
        "fim_avaria_dt",
        "duracao_avaria_min",
        "Sintoma",
        "Objeto",
        "Defeito",
        "Causa",
        "tipo_manutencao"
    ]
]

In [125]:
alarmes_match = alarmes_match.sort_values(
    "Horário do Alarme"
)

manutencoes_match = manutencoes_match.sort_values(
    "inicio_avaria_dt"
)

In [127]:
# Padronizar estação
alarmes_match["estacao_key"] = (
    alarmes_match["estacao_key"]
    .astype(str)
    .str.strip()
    .str.upper()
)

manutencoes_match["estacao_key"] = (
    manutencoes_match["estacao_key"]
    .astype(str)
    .str.strip()
    .str.upper()
)

# Padronizar plataforma
alarmes_match["plataforma_key"] = (
    alarmes_match["plataforma_key"]
    .astype(int)
)

manutencoes_match["plataforma_key"] = (
    manutencoes_match["plataforma_key"]
    .astype(int)
)

# Padronizar porta
alarmes_match["porta_key"] = (
    alarmes_match["porta_key"]
    .astype(int)
)

manutencoes_match["porta_key"] = (
    manutencoes_match["porta_key"]
    .astype(int)
)

In [128]:
print("ALARMES:")
print(
    alarmes_match[
        ["estacao_key", "plataforma_key", "porta_key", "Horário do Alarme"]
    ].dtypes
)

print("\nMANUTENÇÕES:")
print(
    manutencoes_match[
        ["estacao_key", "plataforma_key", "porta_key", "inicio_avaria_dt"]
    ].dtypes
)

ALARMES:
estacao_key                     str
plataforma_key                int64
porta_key                     int64
Horário do Alarme    datetime64[us]
dtype: object

MANUTENÇÕES:
estacao_key                    str
plataforma_key               int64
porta_key                    int64
inicio_avaria_dt    datetime64[us]
dtype: object

In [129]:
alarmes_match = (
    alarmes_match
    .sort_values("Horário do Alarme")
    .reset_index(drop=True)
)

manutencoes_match = (
    manutencoes_match
    .sort_values("inicio_avaria_dt")
    .reset_index(drop=True)
)

In [130]:
base_match = pd.merge_asof(
    alarmes_match,
    manutencoes_match,

    left_on="Horário do Alarme",
    right_on="inicio_avaria_dt",

    by=[
        "estacao_key",
        "plataforma_key",
        "porta_key"
    ],

    direction="nearest"
)

In [131]:
base_match["diferenca_inicio_min"] = (
    (
        base_match["Horário do Alarme"]
        - base_match["inicio_avaria_dt"]
    )
    .abs()
    .dt.total_seconds()
    / 60
)

In [132]:
print("Total de alarmes:", len(base_match))

print(
    "Encontraram manutenção da mesma estação/plataforma/porta:",
    base_match["inicio_avaria_dt"].notna().sum()
)

print("\nDistância entre alarme e início da avaria:")

display(
    base_match["diferenca_inicio_min"].describe(
        percentiles=[
            0.25,
            0.50,
            0.75,
            0.90,
            0.95,
            0.99
        ]
    )
)

Total de alarmes: 103801
Encontraram manutenção da mesma estação/plataforma/porta: 103720

Distância entre alarme e início da avaria:

count    1.037200e+05
mean     7.574155e+04
std      9.616824e+04
min      2.833333e-04
25%      1.178134e+04
50%      4.175850e+04
75%      1.034785e+05
90%      1.950269e+05
95%      2.771799e+05
99%      4.318527e+05
max      1.531419e+06
Name: diferenca_inicio_min, dtype: float64

In [133]:
print("Até 1 minuto:",
      (base_match["diferenca_inicio_min"] <= 1).sum())

print("Até 5 minutos:",
      (base_match["diferenca_inicio_min"] <= 5).sum())

print("Até 10 minutos:",
      (base_match["diferenca_inicio_min"] <= 10).sum())

print("Até 30 minutos:",
      (base_match["diferenca_inicio_min"] <= 30).sum())

print("Até 1 hora:",
      (base_match["diferenca_inicio_min"] <= 60).sum())

print("Até 6 horas:",
      (base_match["diferenca_inicio_min"] <= 360).sum())

print("Até 24 horas:",
      (base_match["diferenca_inicio_min"] <= 1440).sum())

Até 1 minuto: 2549
Até 5 minutos: 4354
Até 10 minutos: 4855
Até 30 minutos: 6913
Até 1 hora: 8298
Até 6 horas: 9926
Até 24 horas: 12412

In [134]:
base_match["alarme_durante_avaria"] = (
    (base_match["Horário do Alarme"] >= base_match["inicio_avaria_dt"])
    &
    (base_match["Horário do Alarme"] <= base_match["fim_avaria_dt"])
)

In [135]:
print(
    "Alarmes durante uma avaria:",
    base_match["alarme_durante_avaria"].sum()
)

print(
    "Percentual:",
    (
        base_match["alarme_durante_avaria"].mean() * 100
    ).round(2),
    "%"
)

Alarmes durante uma avaria: 6988
Percentual: 6.73 %

In [136]:
base_match["diferenca_inicio_assinada_min"] = (
    (
        base_match["Horário do Alarme"]
        - base_match["inicio_avaria_dt"]
    )
    .dt.total_seconds()
    / 60
)

In [137]:
display(
    base_match["diferenca_inicio_assinada_min"].describe(
        percentiles=[
            0.01,
            0.05,
            0.25,
            0.50,
            0.75,
            0.95,
            0.99
        ]
    )
)

count    1.037200e+05
mean     9.236714e+03
std      1.220649e+05
min     -9.826194e+05
1%      -3.236858e+05
5%      -1.842173e+05
25%     -3.413434e+04
50%      6.507709e+02
75%      4.876071e+04
95%      2.063887e+05
99%      3.555263e+05
max      1.531419e+06
Name: diferenca_inicio_assinada_min, dtype: float64

In [138]:
print(
    "Alarme antes da abertura da avaria:",
    (base_match["diferenca_inicio_assinada_min"] < 0).sum()
)

print(
    "Alarme depois da abertura da avaria:",
    (base_match["diferenca_inicio_assinada_min"] >= 0).sum()
)

Alarme antes da abertura da avaria: 43959
Alarme depois da abertura da avaria: 59761

In [139]:
base_match["alarme_durante_avaria"] = (
    (base_match["Horário do Alarme"] >= base_match["inicio_avaria_dt"])
    &
    (base_match["Horário do Alarme"] <= base_match["fim_avaria_dt"])
)

print(
    "Alarmes durante a avaria:",
    base_match["alarme_durante_avaria"].sum()
)

print(
    "Percentual:",
    (
        base_match["alarme_durante_avaria"].mean() * 100
    ).round(2),
    "%"
)

Alarmes durante a avaria: 6988
Percentual: 6.73 %

In [140]:
print(
    "Alarmes até 5 min ANTES da avaria:",
    (
        (base_match["diferenca_inicio_assinada_min"] >= -5)
        &
        (base_match["diferenca_inicio_assinada_min"] < 0)
    ).sum()
)

print(
    "Alarmes até 10 min ANTES da avaria:",
    (
        (base_match["diferenca_inicio_assinada_min"] >= -10)
        &
        (base_match["diferenca_inicio_assinada_min"] < 0)
    ).sum()
)

print(
    "Alarmes até 30 min ANTES da avaria:",
    (
        (base_match["diferenca_inicio_assinada_min"] >= -30)
        &
        (base_match["diferenca_inicio_assinada_min"] < 0)
    ).sum()
)

Alarmes até 5 min ANTES da avaria: 1289
Alarmes até 10 min ANTES da avaria: 1407
Alarmes até 30 min ANTES da avaria: 2067

In [141]:
base_match["associado_avaria"] = (
    base_match["alarme_durante_avaria"]
    |
    (
        (base_match["diferenca_inicio_assinada_min"] >= -5)
        &
        (base_match["diferenca_inicio_assinada_min"] < 0)
    )
)

In [142]:
print(
    base_match["associado_avaria"].value_counts()
)

print(
    base_match["associado_avaria"]
    .value_counts(normalize=True)
    .mul(100)
    .round(2)
)

associado_avaria
False    95524
True      8277
Name: count, dtype: int64
associado_avaria
False    92.03
True      7.97
Name: proportion, dtype: float64

In [143]:
base_match.groupby(
    "associado_avaria"
)["tempo_normalizacao_min"].describe()

,count,mean,std,min,25%,50%,75%,max
associado_avaria,,,,,,,,
False,95524.0,23565.560515,38440.491202,0.0,0.083600,6488.672217,30888.082654,354554.861833
True,8277.0,33013.549482,34750.551566,0.0,5165.058067,22261.636400,48111.529333,289871.077667

In [144]:
print("QUANTIS - SEM AVARIA")
print(
    base_match.loc[
        ~base_match["associado_avaria"],
        "tempo_normalizacao_min"
    ].quantile([
        0.25,
        0.50,
        0.75,
        0.90,
        0.95,
        0.99,
        0.999
    ])
)

print("\nQUANTIS - COM AVARIA")
print(
    base_match.loc[
        base_match["associado_avaria"],
        "tempo_normalizacao_min"
    ].quantile([
        0.25,
        0.50,
        0.75,
        0.90,
        0.95,
        0.99,
        0.999
    ])
)

QUANTIS - SEM AVARIA
0.250         0.083600
0.500      6488.672217
0.750     30888.082654
0.900     73712.315203
0.950    100779.521590
0.990    194744.493217
0.999    240270.850667
Name: tempo_normalizacao_min, dtype: float64

QUANTIS - COM AVARIA
0.250      5165.058067
0.500     22261.636400
0.750     48111.529333
0.900     84742.927400
0.950     93569.581277
0.990    148773.515035
0.999    219410.776684
Name: tempo_normalizacao_min, dtype: float64

In [145]:
print("Até 1 minuto:",
      (base_match["tempo_normalizacao_min"] <= 1).sum())

print("Até 5 minutos:",
      (base_match["tempo_normalizacao_min"] <= 5).sum())

print("Até 10 minutos:",
      (base_match["tempo_normalizacao_min"] <= 10).sum())

print("Até 30 minutos:",
      (base_match["tempo_normalizacao_min"] <= 30).sum())

print("Até 1 hora:",
      (base_match["tempo_normalizacao_min"] <= 60).sum())

print("Até 6 horas:",
      (base_match["tempo_normalizacao_min"] <= 360).sum())

print("Até 24 horas:",
      (base_match["tempo_normalizacao_min"] <= 1440).sum())

print("Acima de 24 horas:",
      (base_match["tempo_normalizacao_min"] > 1440).sum())

Até 1 minuto: 29863
Até 5 minutos: 30212
Até 10 minutos: 30385
Até 30 minutos: 30707
Até 1 hora: 31113
Até 6 horas: 33662
Até 24 horas: 39007
Acima de 24 horas: 64794