# Modelo 5

Nesse notebook, iremos fazer o tratamento restante dos dados, engenharia de features e testar o modelo

In [1]:
from pathlib import Path
import pandas as pd

data_dir = Path.cwd() / "data"

# Se o notebook estiver em uma subpasta, procura a pasta data acima
if not data_dir.exists():
    for pasta in Path.cwd().parents:
        candidato = pasta / "data"
        if candidato.exists():
            data_dir = candidato
            break

# =========================
# Alarmes
# =========================
alarmes = pd.read_excel(
    data_dir / "Alarmes" / "Histórico de alarmes 23-26.xlsx"
)

# =========================
# Corretiva emergencial
# =========================
emergencial = pd.read_excel(
    data_dir
    / "Corretiva Emergencial"
    / "processados"
    / "ZM01_limpa.xlsx"
)

# =========================
# Corretiva programada
# =========================
programada = pd.read_excel(
    data_dir
    / "Corretiva Programada"
    / "processados"
    / "ZM02_limpa.xlsx"
)

# =========================
# Preventiva
# =========================
preventiva = pd.read_csv(
    data_dir
    / "Preventiva"
    / "preventiva_zm03_limpa.csv"
)

# =========================
# Fluxo / Catracas
# =========================
fluxo = pd.read_excel(
    data_dir
    / "Catracas"
    / "Historico L4.xlsx"
)

In [2]:
print("Alarmes:", alarmes.shape)
print("Emergencial:", emergencial.shape)
print("Programada:", programada.shape)
print("Preventiva:", preventiva.shape)
print("Fluxo:", fluxo.shape)

Alarmes: (1039871, 7)
Emergencial: (10543, 27)
Programada: (1163, 27)
Preventiva: (569, 19)
Fluxo: (1312, 32)

In [3]:
print("\nAlarmes:")
print(alarmes.columns.tolist())

print("\nEmergencial:")
print(emergencial.columns.tolist())

print("\nProgramada:")
print(programada.columns.tolist())

print("\nPreventiva:")
print(preventiva.columns.tolist())

print("\nFluxo:")
print(fluxo.columns.tolist())

Alarmes:
['TAG', 'Horário do Alarme', 'Estação', 'Porta', 'Alarme', 'Horário da Normalizacao', 'Tempo de Normalização']

Emergencial:
['linha_origem', 'tipo_de_nota', 'nota', 'ordem', 'perfil_do_catalogo', 'descricao', 'local_de_instalacao', 'centro_de_trabalho_responsavel', 'inicio_avaria_datetime', 'fim_avaria_datetime', 'duracao_avaria_horas', 'analise_datetime', 'encerramento_datetime', 'indisponivel_flag', 'falha_flag', 'analisada_flag', 'ordem_ausente_flag', 'ordem_repetida_flag', 'comentarios_classificacao_engenharia', 'status_do_usuario_da_ordem', 'texto_longo_da_ordem', 'status_do_sistema_da_ordem', 'sintoma', 'objeto', 'defeito', 'causa', 'acao']

Programada:
['linha_origem', 'tipo_de_nota', 'nota', 'ordem', 'perfil_do_catalogo', 'descricao', 'local_de_instalacao', 'centro_de_trabalho_responsavel', 'inicio_avaria_datetime', 'fim_avaria_datetime', 'duracao_avaria_horas', 'encerramento_datetime', 'indisponivel_flag', 'analisada_flag', 'ordem_ausente_flag', 'ordem_repetida_flag', 'nota_repetida_flag', 'duracao_extrema_flag', 'duracao_zero_flag', 'status_do_usuario_da_ordem', 'texto_longo_da_ordem', 'status_do_sistema_da_ordem', 'sintoma', 'objeto', 'defeito', 'causa', 'acao']

Preventiva:
['Ordem', 'Tipo de ordem', 'Centro de trabalho', 'Local de instalação', 'Texto breve', 'Plano de manutenção', 'Status usuário', 'Status do sistema', 'Data-base do início', 'Hr.início programada', 'Data-base do fim', 'Fim-base (hora)', 'DT_Inicio', 'DT_Fim', 'duracao_h', 'Estacao_Centro', 'Estacao_Local', 'Estacao', 'cancelada']

Fluxo:
['Unnamed: 0', 'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4', 'Unnamed: 5', 'Unnamed: 6', 'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9', 'Unnamed: 10', 'Unnamed: 11', 'Unnamed: 12', 'Unnamed: 13', 'Unnamed: 14', 'Unnamed: 15', 'Unnamed: 16', 'Unnamed: 17', 'Unnamed: 18', 'Unnamed: 19', 'Unnamed: 20', 'Unnamed: 21', 'Unnamed: 22', 'Unnamed: 23', 'Unnamed: 24', 'Unnamed: 25', 'Unnamed: 26', 'Unnamed: 27', 'Unnamed: 28', 'Unnamed: 29', 'Unnamed: 30', 'Unnamed: 31']

In [4]:
# ==========================================
# PADRONIZAÇÃO DOS NOMES DAS COLUNAS
# ==========================================

# Alarmes PSD
alarmes = alarmes.rename(columns={
    "TAG": "tag_alarme",
    "Horário do Alarme": "horario_alarme",
    "Estação": "estacao",
    "Porta": "porta",
    "Alarme": "tipo_alarme",
    "Horário da Normalizacao": "horario_normalizacao_alarme",
    "Tempo de Normalização": "tempo_normalizacao_alarme"
})


# Corretiva emergencial
emergencial = emergencial.rename(
    columns={
        coluna: f"{coluna}_emergencial"
        for coluna in emergencial.columns
    }
)


# Corretiva programada
programada = programada.rename(
    columns={
        coluna: f"{coluna}_programada"
        for coluna in programada.columns
    }
)


# Preventiva
preventiva = preventiva.rename(columns={
    "Ordem": "ordem_preventiva",
    "Tipo de ordem": "tipo_ordem_preventiva",
    "Centro de trabalho": "centro_trabalho_preventiva",
    "Local de instalação": "local_instalacao_preventiva",
    "Texto breve": "texto_breve_preventiva",
    "Plano de manutenção": "plano_manutencao_preventiva",
    "Status usuário": "status_usuario_preventiva",
    "Status do sistema": "status_sistema_preventiva",
    "Data-base do início": "data_inicio_preventiva",
    "Hr.início programada": "hora_inicio_preventiva",
    "Data-base do fim": "data_fim_preventiva",
    "Fim-base (hora)": "hora_fim_preventiva",
    "DT_Inicio": "inicio_preventiva",
    "DT_Fim": "fim_preventiva",
    "duracao_h": "duracao_h_preventiva",
    "Estacao_Centro": "estacao_centro_preventiva",
    "Estacao_Local": "estacao_local_preventiva",
    "Estacao": "estacao",
    "cancelada": "cancelada_preventiva"
})

In [5]:
fluxo_bruto = pd.read_excel(
    data_dir / "Catracas" / "Historico L4.xlsx",
    header=None
)

pd.set_option("display.max_columns", None)

display(
    fluxo_bruto.head(10)
)

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,Integrações - Contadores,NaN,NaN,NaN,NaN,Estações Bloqueios,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Totais,NaN
3,NaN,NaN,Integração Linha 9 - Pinheiros,NaN,Integração Linha 2 - Paulista,NaN,Integração Linha 3 - República,NaN,Integração Linha 1 - Luz,NaN,Butantã,NaN,Pinheiros,NaN,Faria Lima,NaN,Paulista,NaN,Luz,NaN,Fradique Coutinho,NaN,Higienópolis Mackenzie,NaN,Oscar Freire,NaN,São Paulo Morumbi,NaN,Vila Sônia,NaN,Total,NaN
4,NaN,Data,Entrada,Saída,Entrada,Saída,Entrada,Saída,Entrada,Saída,Entrada,Saída,Entrada,Saída,Entrada,Saída,Entrada,Saída,Entrada,Saída,Entrada,Saída,Entrada,Saída,Entrada,Saída,Entrada,Saída,Entrada,Saída,Total Entradas,Total Saídas
5,NaN,2023-01-01 00:00:00,14810,18420,21100,15491,20938,27570,26137,31636,6187,8084,829,1168,3207,2941,17027,3860,1219,1594,1971,1773,5760,3159,2823,2591,3524,4898,7228,10051,132760,128338
6,NaN,2023-01-02 00:00:00,55014,52915,43654,43776,60603,62160,79708,74912,18813,18418,4688,5216,17558,18249,9805,11225,3810,3857,8320,8288,9100,10092,13050,12222,12169,13107,24383,24280,360675,358717
7,NaN,2023-01-03 00:00:00,68274,66002,55876,55034,74315,77658,94899,90480,22796,21030,6502,6867,23065,23693,11819,13598,4718,4604,11022,10872,11144,12256,16405,14761,14995,15617,29301,28967,445131,441439
8,NaN,2023-01-04 00:00:00,72074,69470,59432,57883,78793,83311,96180,93408,23399,42844,6794,14912,24327,50270,12104,27652,4638,9732,12040,23318,11895,25380,17182,30994,15616,31988,29802,58551,464276,619713
9,NaN,2023-01-05 00:00:00,72248,70032,60647,59758,79757,83282,97243,94560,23681,21122,6984,7527,25337,26178,12612,14423,4831,4931,12534,12493,12435,13397,18135,16246,15977,16489,30610,29864,473031,470302

In [6]:
# ==========================================
# TRATAMENTO DO FLUXO DE PASSAGEIROS
# ==========================================

# Dados começam na linha 5
fluxo_dados = fluxo_bruto.iloc[5:].copy()

# Data está na coluna 1
fluxo_dados["data"] = pd.to_datetime(
    fluxo_dados[1],
    errors="coerce"
)

# Mapeamento das estações:
# coluna de entrada, coluna de saída
estacoes_fluxo = {
    "BUT": (10, 11),   # Butantã
    "PIN": (12, 13),   # Pinheiros
    "FAL": (14, 15),   # Faria Lima
    "PTA": (16, 17),   # Paulista
    "LUZ": (18, 19),   # Luz
    "FRA": (20, 21),   # Fradique Coutinho
    "HIG": (22, 23),   # Higienópolis-Mackenzie
    "FRE": (24, 25),   # Oscar Freire
    "MBI": (26, 27),   # São Paulo-Morumbi
    "VSO": (28, 29)    # Vila Sônia
}

fluxo_lista = []

for estacao, (col_entrada, col_saida) in estacoes_fluxo.items():

    temp = pd.DataFrame({
        "data": fluxo_dados["data"],
        "estacao": estacao,
        "entrada_fluxo": pd.to_numeric(
            fluxo_dados[col_entrada],
            errors="coerce"
        ),
        "saida_fluxo": pd.to_numeric(
            fluxo_dados[col_saida],
            errors="coerce"
        )
    })

    fluxo_lista.append(temp)

fluxo = pd.concat(
    fluxo_lista,
    ignore_index=True
)

# Remover linhas sem data
fluxo = fluxo.dropna(
    subset=["data"]
)

# Fluxo total da estação no dia
fluxo["total_fluxo"] = (
    fluxo["entrada_fluxo"]
    + fluxo["saida_fluxo"]
)

fluxo = fluxo.sort_values(
    ["data", "estacao"]
).reset_index(drop=True)

display(fluxo.head(20))

         data estacao  entrada_fluxo  saida_fluxo  total_fluxo
0  2023-01-01     BUT           6187         8084        14271
1  2023-01-01     FAL           3207         2941         6148
2  2023-01-01     FRA           1971         1773         3744
3  2023-01-01     FRE           2823         2591         5414
4  2023-01-01     HIG           5760         3159         8919
5  2023-01-01     LUZ           1219         1594         2813
6  2023-01-01     MBI           3524         4898         8422
7  2023-01-01     PIN            829         1168         1997
8  2023-01-01     PTA          17027         3860        20887
9  2023-01-01     VSO           7228        10051        17279
10 2023-01-02     BUT          18813        18418        37231
11 2023-01-02     FAL          17558        18249        35807
12 2023-01-02     FRA           8320         8288        16608
13 2023-01-02     FRE          13050        12222        25272
14 2023-01-02     HIG           9100        10092        19192
15 2023-01-02     LUZ           3810         3857         7667
16 2023-01-02     MBI          12169        13107        25276
17 2023-01-02     PIN           4688         5216         9904
18 2023-01-02     PTA           9805        11225        21030
19 2023-01-02     VSO          24383        24280        48663

In [7]:
print("Emergencial:")
display(
    emergencial[
        ["local_de_instalacao_emergencial"]
    ]
    .dropna()
    .drop_duplicates()
    .head(30)
)

print("\nProgramada:")
display(
    programada[
        ["local_de_instalacao_programada"]
    ]
    .dropna()
    .drop_duplicates()
    .head(30)
)

Emergencial:

    local_de_instalacao_emergencial
0                    SP04-6-PSD-BUT
2               SP04-6-PSD-BUT-P1S1
4         SP04-6-PSD-BUT-P1S1-PSSE1
6               SP04-6-PSD-BUT-P2S1
7         SP04-6-PSD-BUT-P2S1-PSSE2
8               SP04-6-PSD-BUT-PLT1
18      SP04-6-PSD-BUT-PLT1-PP01PDM
34      SP04-6-PSD-BUT-PLT1-PP02PDM
53      SP04-6-PSD-BUT-PLT1-PP03PDM
62      SP04-6-PSD-BUT-PLT1-PP04PDM
69      SP04-6-PSD-BUT-PLT1-PP05PDM
80      SP04-6-PSD-BUT-PLT1-PP06PDM
91      SP04-6-PSD-BUT-PLT1-PP07PDM
97      SP04-6-PSD-BUT-PLT1-PP08PDM
109     SP04-6-PSD-BUT-PLT1-PP09PDM
118     SP04-6-PSD-BUT-PLT1-PP10PDM
142     SP04-6-PSD-BUT-PLT1-PP11PDM
153     SP04-6-PSD-BUT-PLT1-PP12PDM
159     SP04-6-PSD-BUT-PLT1-PP13PDM
192     SP04-6-PSD-BUT-PLT1-PP14PDM
200     SP04-6-PSD-BUT-PLT1-PP15PDM
205     SP04-6-PSD-BUT-PLT1-PP16PDM
230     SP04-6-PSD-BUT-PLT1-PP17PDM
242     SP04-6-PSD-BUT-PLT1-PP18PDM
256     SP04-6-PSD-BUT-PLT1-PP19PDM
264     SP04-6-PSD-BUT-PLT1-PP20PDM
276     SP04-6-PSD-BUT-PLT1-PP21PDM
311     SP04-6-PSD-BUT-PLT1-PP22PDM
330     SP04-6-PSD-BUT-PLT1-PP22PFX
331     SP04-6-PSD-BUT-PLT1-PP23PDM

Programada:

   local_de_instalacao_programada
0                  SP04-6-PSD-BUT
1             SP04-6-PSD-BUT-P1S1
2       SP04-6-PSD-BUT-P2S1-PSSE2
4             SP04-6-PSD-BUT-PLT1
6        SP04-6-PSD-BUT-PLT1-PFP1
7     SP04-6-PSD-BUT-PLT1-PP05PDM
8     SP04-6-PSD-BUT-PLT1-PP06PSE
9     SP04-6-PSD-BUT-PLT1-PP10PDM
10    SP04-6-PSD-BUT-PLT1-PP15PDM
11    SP04-6-PSD-BUT-PLT1-PP15PSE
12    SP04-6-PSD-BUT-PLT1-PP18PDM
13    SP04-6-PSD-BUT-PLT1-PP18PSE
14    SP04-6-PSD-BUT-PLT1-PP19PDM
15    SP04-6-PSD-BUT-PLT1-PP23PDM
16    SP04-6-PSD-BUT-PLT1-PP24PDM
17            SP04-6-PSD-BUT-PLT2
18       SP04-6-PSD-BUT-PLT2-PFP2
19    SP04-6-PSD-BUT-PLT2-PP04PDM
20    SP04-6-PSD-BUT-PLT2-PP05PDM
21    SP04-6-PSD-BUT-PLT2-PP06PDM
22    SP04-6-PSD-BUT-PLT2-PP08PDM
25    SP04-6-PSD-BUT-PLT2-PP10PDM
27    SP04-6-PSD-BUT-PLT2-PP12PDM
28    SP04-6-PSD-BUT-PLT2-PP15PDM
29    SP04-6-PSD-BUT-PLT2-PP16PDM
30    SP04-6-PSD-BUT-PLT2-PP16PSE
31    SP04-6-PSD-BUT-PLT2-PP18PDM
32    SP04-6-PSD-BUT-PLT2-PP18PSE
33    SP04-6-PSD-BUT-PLT2-PP19PDM
34    SP04-6-PSD-BUT-PLT2-PP24PSE

In [8]:
print("Quantidade de locais distintos - Emergencial:")
print(
    emergencial[
        "local_de_instalacao_emergencial"
    ].nunique()
)

print("\nQuantidade de locais distintos - Programada:")
print(
    programada[
        "local_de_instalacao_programada"
    ].nunique()
)

Quantidade de locais distintos - Emergencial:
691

Quantidade de locais distintos - Programada:
582

In [9]:
# ==========================================
# CHAVES DE LOCALIZAÇÃO - EMERGENCIAL
# ==========================================

local_emergencial = (
    emergencial["local_de_instalacao_emergencial"]
    .astype("string")
    .str.upper()
    .str.strip()
)

# Estação: código logo após PSD-
emergencial["estacao"] = local_emergencial.str.extract(
    r"PSD-([A-Z]{3})(?:-|$)",
    expand=False
)

# Plataforma: somente quando explicitamente aparece PLT1 ou PLT2
emergencial["plataforma"] = local_emergencial.str.extract(
    r"-PLT(\d+)",
    expand=False
)

# Porta: PP01, PP02, PP24 etc.
emergencial["porta"] = local_emergencial.str.extract(
    r"-PP(\d+)",
    expand=False
)


# ==========================================
# CHAVES DE LOCALIZAÇÃO - PROGRAMADA
# ==========================================

local_programada = (
    programada["local_de_instalacao_programada"]
    .astype("string")
    .str.upper()
    .str.strip()
)

programada["estacao"] = local_programada.str.extract(
    r"PSD-([A-Z]{3})(?:-|$)",
    expand=False
)

programada["plataforma"] = local_programada.str.extract(
    r"-PLT(\d+)",
    expand=False
)

programada["porta"] = local_programada.str.extract(
    r"-PP(\d+)",
    expand=False
)

In [10]:
# Plataforma como texto padronizado
emergencial["plataforma"] = (
    emergencial["plataforma"]
    .astype("string")
)

programada["plataforma"] = (
    programada["plataforma"]
    .astype("string")
)

# Porta sempre com dois dígitos
emergencial["porta"] = (
    emergencial["porta"]
    .astype("string")
    .str.zfill(2)
)

programada["porta"] = (
    programada["porta"]
    .astype("string")
    .str.zfill(2)
)

In [11]:
# ==========================================
# GRANULARIDADE DA LOCALIZAÇÃO
# ==========================================

emergencial["granularidade_localizacao"] = "sem_localizacao"

emergencial.loc[
    emergencial["estacao"].notna(),
    "granularidade_localizacao"
] = "estacao"

emergencial.loc[
    emergencial["plataforma"].notna(),
    "granularidade_localizacao"
] = "plataforma"

emergencial.loc[
    emergencial["porta"].notna(),
    "granularidade_localizacao"
] = "porta"


programada["granularidade_localizacao"] = "sem_localizacao"

programada.loc[
    programada["estacao"].notna(),
    "granularidade_localizacao"
] = "estacao"

programada.loc[
    programada["plataforma"].notna(),
    "granularidade_localizacao"
] = "plataforma"

programada.loc[
    programada["porta"].notna(),
    "granularidade_localizacao"
] = "porta"

In [12]:
print("EMERGENCIAL")
print(
    emergencial["granularidade_localizacao"]
    .value_counts(dropna=False)
)

print("\nPROGRAMADA")
print(
    programada["granularidade_localizacao"]
    .value_counts(dropna=False)
)

EMERGENCIAL
granularidade_localizacao
porta         9360
plataforma     940
estacao        243
Name: count, dtype: int64

PROGRAMADA
granularidade_localizacao
porta         1014
estacao         76
plataforma      73
Name: count, dtype: int64

In [13]:
display(
    emergencial[
        [
            "local_de_instalacao_emergencial",
            "estacao",
            "plataforma",
            "porta",
            "granularidade_localizacao"
        ]
    ].head(30)
)

display(
    programada[
        [
            "local_de_instalacao_programada",
            "estacao",
            "plataforma",
            "porta",
            "granularidade_localizacao"
        ]
    ].head(30)
)

,local_de_instalacao_emergencial,estacao,plataforma,porta,granularidade_localizacao
0,SP04-6-PSD-BUT,BUT,<NA>,<NA>,estacao
1,SP04-6-PSD-BUT,BUT,<NA>,<NA>,estacao
2,SP04-6-PSD-BUT-P1S1,BUT,<NA>,<NA>,estacao
3,SP04-6-PSD-BUT-P1S1,BUT,<NA>,<NA>,estacao
4,SP04-6-PSD-BUT-P1S1-PSSE1,BUT,<NA>,<NA>,estacao
5,SP04-6-PSD-BUT-P1S1-PSSE1,BUT,<NA>,<NA>,estacao
6,SP04-6-PSD-BUT-P2S1,BUT,<NA>,<NA>,estacao
7,SP04-6-PSD-BUT-P2S1-PSSE2,BUT,<NA>,<NA>,estacao
8,SP04-6-PSD-BUT-PLT1,BUT,1,<NA>,plataforma
9,SP04-6-PSD-BUT-PLT1,BUT,1,<NA>,plataforma
10,SP04-6-PSD-BUT-PLT1,BUT,1,<NA>,plataforma
11,SP04-6-PSD-BUT-PLT1,BUT,1,<NA>,plataforma
12,SP04-6-PSD-BUT-PLT1,BUT,1,<NA>,plataforma
13,SP04-6-PSD-BUT-PLT1,BUT,1,<NA>,plataforma
14,SP04-6-PSD-BUT-PLT1,BUT,1,<NA>,plataforma
15,SP04-6-PSD-BUT-PLT1,BUT,1,<NA>,plataforma
16,SP04-6-PSD-BUT-PLT1,BUT,1,<NA>,plataforma
17,SP04-6-PSD-BUT-PLT1,BUT,1,<NA>,plataforma
18,SP04-6-PSD-BUT-PLT1-PP01PDM,BUT,1,01,porta
19,SP04-6-PSD-BUT-PLT1-PP01PDM,BUT,1,01,porta
20,SP04-6-PSD-BUT-PLT1-PP01PDM,BUT,1,01,porta
21,SP04-6-PSD-BUT-PLT1-PP01PDM,BUT,1,01,porta
22,SP04-6-PSD-BUT-PLT1-PP01PDM,BUT,1,01,porta
23,SP04-6-PSD-BUT-PLT1-PP01PDM,BUT,1,01,porta
24,SP04-6-PSD-BUT-PLT1-PP01PDM,BUT,1,01,porta
25,SP04-6-PSD-BUT-PLT1-PP01PDM,BUT,1,01,porta
26,SP04-6-PSD-BUT-PLT1-PP01PDM,BUT,1,01,porta
27,SP04-6-PSD-BUT-PLT1-PP01PDM,BUT,1,01,porta
28,SP04-6-PSD-BUT-PLT1-PP01PDM,BUT,1,01,porta
29,SP04-6-PSD-BUT-PLT1-PP01PDM,BUT,1,01,porta

,local_de_instalacao_programada,estacao,plataforma,porta,granularidade_localizacao
0,SP04-6-PSD-BUT,BUT,<NA>,<NA>,estacao
1,SP04-6-PSD-BUT-P1S1,BUT,<NA>,<NA>,estacao
2,SP04-6-PSD-BUT-P2S1-PSSE2,BUT,<NA>,<NA>,estacao
3,SP04-6-PSD-BUT-P2S1-PSSE2,BUT,<NA>,<NA>,estacao
4,SP04-6-PSD-BUT-PLT1,BUT,1,<NA>,plataforma
5,SP04-6-PSD-BUT-PLT1,BUT,1,<NA>,plataforma
6,SP04-6-PSD-BUT-PLT1-PFP1,BUT,1,<NA>,plataforma
7,SP04-6-PSD-BUT-PLT1-PP05PDM,BUT,1,05,porta
8,SP04-6-PSD-BUT-PLT1-PP06PSE,BUT,1,06,porta
9,SP04-6-PSD-BUT-PLT1-PP10PDM,BUT,1,10,porta
10,SP04-6-PSD-BUT-PLT1-PP15PDM,BUT,1,15,porta
11,SP04-6-PSD-BUT-PLT1-PP15PSE,BUT,1,15,porta
12,SP04-6-PSD-BUT-PLT1-PP18PDM,BUT,1,18,porta
13,SP04-6-PSD-BUT-PLT1-PP18PSE,BUT,1,18,porta
14,SP04-6-PSD-BUT-PLT1-PP19PDM,BUT,1,19,porta
15,SP04-6-PSD-BUT-PLT1-PP23PDM,BUT,1,23,porta
16,SP04-6-PSD-BUT-PLT1-PP24PDM,BUT,1,24,porta
17,SP04-6-PSD-BUT-PLT2,BUT,2,<NA>,plataforma
18,SP04-6-PSD-BUT-PLT2-PFP2,BUT,2,<NA>,plataforma
19,SP04-6-PSD-BUT-PLT2-PP04PDM,BUT,2,04,porta
20,SP04-6-PSD-BUT-PLT2-PP05PDM,BUT,2,05,porta
21,SP04-6-PSD-BUT-PLT2-PP06PDM,BUT,2,06,porta
22,SP04-6-PSD-BUT-PLT2-PP08PDM,BUT,2,08,porta
23,SP04-6-PSD-BUT-PLT2-PP08PDM,BUT,2,08,porta
24,SP04-6-PSD-BUT-PLT2-PP08PDM,BUT,2,08,porta
25,SP04-6-PSD-BUT-PLT2-PP10PDM,BUT,2,10,porta
26,SP04-6-PSD-BUT-PLT2-PP10PDM,BUT,2,10,porta
27,SP04-6-PSD-BUT-PLT2-PP12PDM,BUT,2,12,porta
28,SP04-6-PSD-BUT-PLT2-PP15PDM,BUT,2,15,porta
29,SP04-6-PSD-BUT-PLT2-PP16PDM,BUT,2,16,porta

In [14]:
print("EMERGENCIAL")
print(
    emergencial["granularidade_localizacao"]
    .value_counts(dropna=False)
)

print("\nPROGRAMADA")
print(
    programada["granularidade_localizacao"]
    .value_counts(dropna=False)
)

EMERGENCIAL
granularidade_localizacao
porta         9360
plataforma     940
estacao        243
Name: count, dtype: int64

PROGRAMADA
granularidade_localizacao
porta         1014
estacao         76
plataforma      73
Name: count, dtype: int64

In [15]:
print("\nPercentuais - Emergencial")
print(
    emergencial["granularidade_localizacao"]
    .value_counts(normalize=True)
    .mul(100)
    .round(2)
)

print("\nPercentuais - Programada")
print(
    programada["granularidade_localizacao"]
    .value_counts(normalize=True)
    .mul(100)
    .round(2)
)

Percentuais - Emergencial
granularidade_localizacao
porta         88.78
plataforma     8.92
estacao        2.30
Name: proportion, dtype: float64

Percentuais - Programada
granularidade_localizacao
porta         87.19
estacao        6.53
plataforma     6.28
Name: proportion, dtype: float64

In [16]:
# ==========================================
# EVENTOS ELEGÍVEIS PARA O TARGET
# ==========================================

emergencial["elegivel_target"] = (
    emergencial["granularidade_localizacao"] == "porta"
)

print("Total de manutenções emergenciais:")
print(len(emergencial))

print("\nManutenções emergenciais no nível de porta:")
print(emergencial["elegivel_target"].sum())

print("\nPercentual elegível para o target:")
print(
    round(
        emergencial["elegivel_target"].mean() * 100,
        2
    )
)

Total de manutenções emergenciais:
10543

Manutenções emergenciais no nível de porta:
9360

Percentual elegível para o target:
88.78

In [17]:
# Garantir datetime
emergencial["inicio_avaria_datetime_emergencial"] = pd.to_datetime(
    emergencial["inicio_avaria_datetime_emergencial"],
    errors="coerce"
)

programada["inicio_avaria_datetime_programada"] = pd.to_datetime(
    programada["inicio_avaria_datetime_programada"],
    errors="coerce"
)

alarmes["horario_alarme"] = pd.to_datetime(
    alarmes["horario_alarme"],
    errors="coerce"
)

preventiva["inicio_preventiva"] = pd.to_datetime(
    preventiva["inicio_preventiva"],
    errors="coerce"
)

print("ALARMES")
print(alarmes["horario_alarme"].min())
print(alarmes["horario_alarme"].max())

print("\nEMERGENCIAL")
print(emergencial["inicio_avaria_datetime_emergencial"].min())
print(emergencial["inicio_avaria_datetime_emergencial"].max())

print("\nPROGRAMADA")
print(programada["inicio_avaria_datetime_programada"].min())
print(programada["inicio_avaria_datetime_programada"].max())

print("\nPREVENTIVA")
print(preventiva["inicio_preventiva"].min())
print(preventiva["inicio_preventiva"].max())

print("\nFLUXO")
print(fluxo["data"].min())
print(fluxo["data"].max())

ALARMES
2023-02-27 06:26:56.897000
2025-12-31 23:57:02

EMERGENCIAL
2023-01-01 02:39:00
2026-04-01 22:43:00

PROGRAMADA
2023-01-03 03:55:59
2026-03-28 14:15:00

PREVENTIVA
2022-12-26 05:30:00
2026-03-30 21:30:00

FLUXO
2023-01-01 00:00:00
2026-07-31 00:00:00

In [18]:
# ==========================================
# JANELA TEMPORAL DA MODELAGEM
# ==========================================

inicio_modelagem = pd.Timestamp("2023-02-27")
fim_modelagem = pd.Timestamp("2025-12-31 23:59:59")

horizonte_predicao = pd.Timedelta(days=7)

print("Início da modelagem:", inicio_modelagem)
print("Fim da modelagem:", fim_modelagem)

print(
    "Precisamos de registros emergenciais até:",
    fim_modelagem + horizonte_predicao
)

Início da modelagem: 2023-02-27 00:00:00
Fim da modelagem: 2025-12-31 23:59:59
Precisamos de registros emergenciais até: 2026-01-07 23:59:59

In [19]:
# ==========================================
# EXTRAÇÃO GENERALIZADA DA LOCALIZAÇÃO
# DOS ALARMES PSD
# ==========================================

tag = (
    alarmes["tag_alarme"]
    .astype("string")
    .str.upper()
    .str.strip()
)

# ------------------------------------------------
# PADRÃO 1
# Exemplos:
# PSD_FAL_FAL2_PDM09_OBS
# PSD_FAL_FAL2_MDU09_STS
# ------------------------------------------------

padrao_1 = tag.str.extract(
    r"^PSD_([A-Z]{3})_[A-Z]{3}(\d+)_(?:PDM|MDU)(\d+)"
)

# ------------------------------------------------
# PADRÃO 2
# Exemplos:
# PSD_P_FRA2_PDM22_FO
# PSD_P_MBI1_PDM13LSD
# PSD_P_MBI1_MDU22STS
# ------------------------------------------------

padrao_2 = tag.str.extract(
    r"^PSD_P_([A-Z]{3})(\d+)_(?:PDM|MDU)(\d+)"
)

# Combinar os dois padrões
alarmes["estacao_tag"] = (
    padrao_1[0]
    .fillna(padrao_2[0])
)

alarmes["plataforma"] = (
    padrao_1[1]
    .fillna(padrao_2[1])
)

alarmes["porta_tag"] = (
    padrao_1[2]
    .fillna(padrao_2[2])
)

# Padronizar
alarmes["estacao_tag"] = (
    alarmes["estacao_tag"]
    .astype("string")
    .str.upper()
)

alarmes["plataforma"] = (
    alarmes["plataforma"]
    .astype("string")
)

alarmes["porta_tag"] = (
    alarmes["porta_tag"]
    .astype("string")
    .str.zfill(2)
)

alarmes["porta"] = (
    alarmes["porta"]
    .astype("string")
    .str.extract(r"(\d+)", expand=False)
    .str.zfill(2)
)

alarmes["estacao"] = (
    alarmes["estacao"]
    .astype("string")
    .str.upper()
    .str.strip()
)

In [20]:
print("Total de alarmes:")
print(len(alarmes))

print("\nCom plataforma identificada:")
print(alarmes["plataforma"].notna().sum())

print("\nPercentual com localização:")
print(
    round(
        alarmes["plataforma"].notna().mean() * 100,
        2
    ),
    "%"
)

print("\nConcordância da estação:")
mask_estacao = alarmes["estacao_tag"].notna()

print(
    (
        alarmes.loc[mask_estacao, "estacao"]
        ==
        alarmes.loc[mask_estacao, "estacao_tag"]
    ).mean()
)

print("\nConcordância da porta:")
mask_porta = alarmes["porta_tag"].notna()

print(
    (
        alarmes.loc[mask_porta, "porta"]
        ==
        alarmes.loc[mask_porta, "porta_tag"]
    ).mean()
)

Total de alarmes:
1039871

Com plataforma identificada:
1039685

Percentual com localização:
99.98 %

Concordância da estação:
1.0

Concordância da porta:
1.0

In [21]:
restantes = alarmes[
    alarmes["plataforma"].isna()
].copy()

restantes["estrutura_tag"] = (
    restantes["tag_alarme"]
    .astype("string")
    .str.upper()
    .str.replace(r"\d+", "<N>", regex=True)
)

print("\nAlarmes ainda não mapeados:")
print(len(restantes))

print("\nEstruturas restantes mais frequentes:")

print(
    restantes["estrutura_tag"]
    .value_counts()
    .head(30)
)

Alarmes ainda não mapeados:
186

Estruturas restantes mais frequentes:
estrutura_tag
PSD_P_LUZ<N>_CBTC_BIM_FAULT_VALUE    186
Name: count, dtype: Int64

In [22]:
# ==========================================
# CHAVE ÚNICA DE PORTA
# ==========================================

alarmes["chave_porta"] = (
    alarmes["estacao"].astype("string")
    + "_P" + alarmes["plataforma"].astype("string")
    + "_D" + alarmes["porta"].astype("string")
)

emergencial["chave_porta"] = (
    emergencial["estacao"].astype("string")
    + "_P" + emergencial["plataforma"].astype("string")
    + "_D" + emergencial["porta"].astype("string")
)

programada["chave_porta"] = (
    programada["estacao"].astype("string")
    + "_P" + programada["plataforma"].astype("string")
    + "_D" + programada["porta"].astype("string")
)

In [23]:
alarmes.loc[
    alarmes[["estacao", "plataforma", "porta"]].isna().any(axis=1),
    "chave_porta"
] = pd.NA

emergencial.loc[
    emergencial[["estacao", "plataforma", "porta"]].isna().any(axis=1),
    "chave_porta"
] = pd.NA

programada.loc[
    programada[["estacao", "plataforma", "porta"]].isna().any(axis=1),
    "chave_porta"
] = pd.NA

In [24]:
print("Alarmes com chave_porta:")
print(alarmes["chave_porta"].notna().sum())

print("\nEmergenciais com chave_porta:")
print(emergencial["chave_porta"].notna().sum())

print("\nProgramadas com chave_porta:")
print(programada["chave_porta"].notna().sum())

print("\nExemplos:")
display(
    alarmes[
        ["estacao", "plataforma", "porta", "chave_porta"]
    ].dropna().head(10)
)

Alarmes com chave_porta:
1039685

Emergenciais com chave_porta:
9357

Programadas com chave_porta:
1010

Exemplos:

  estacao plataforma porta chave_porta
0     BUT          1    02  BUT_P1_D02
1     BUT          1    02  BUT_P1_D02
2     BUT          1    02  BUT_P1_D02
3     BUT          1    02  BUT_P1_D02
4     BUT          1    02  BUT_P1_D02
5     BUT          1    02  BUT_P1_D02
6     BUT          1    02  BUT_P1_D02
7     BUT          1    02  BUT_P1_D02
8     BUT          1    02  BUT_P1_D02
9     BUT          1    02  BUT_P1_D02

In [25]:
# ==========================================
# LOCALIZAÇÃO - MANUTENÇÃO PREVENTIVA
# ==========================================

local_preventiva = (
    preventiva["local_instalacao_preventiva"]
    .astype("string")
    .str.upper()
    .str.strip()
)

# Estação
preventiva["estacao"] = local_preventiva.str.extract(
    r"PSD-([A-Z]{3})(?:-|$)",
    expand=False
)

# Plataforma
preventiva["plataforma"] = local_preventiva.str.extract(
    r"-PLT(\d+)",
    expand=False
)

# Porta, somente se existir explicitamente PPxx
preventiva["porta"] = local_preventiva.str.extract(
    r"-PP(\d+)",
    expand=False
)

# Padronização
preventiva["plataforma"] = (
    preventiva["plataforma"]
    .astype("string")
)

preventiva["porta"] = (
    preventiva["porta"]
    .astype("string")
    .str.zfill(2)
)

In [26]:
preventiva["granularidade_localizacao"] = "sem_localizacao"

preventiva.loc[
    preventiva["estacao"].notna(),
    "granularidade_localizacao"
] = "estacao"

preventiva.loc[
    preventiva["plataforma"].notna(),
    "granularidade_localizacao"
] = "plataforma"

preventiva.loc[
    preventiva["porta"].notna(),
    "granularidade_localizacao"
] = "porta"

In [27]:
preventiva["chave_porta"] = (
    preventiva["estacao"].astype("string")
    + "_P" + preventiva["plataforma"].astype("string")
    + "_D" + preventiva["porta"].astype("string")
)

preventiva.loc[
    preventiva[
        ["estacao", "plataforma", "porta"]
    ].isna().any(axis=1),
    "chave_porta"
] = pd.NA

In [28]:
print("Granularidade da preventiva:")
print(
    preventiva["granularidade_localizacao"]
    .value_counts(dropna=False)
)

print("\nPercentuais:")
print(
    preventiva["granularidade_localizacao"]
    .value_counts(normalize=True)
    .mul(100)
    .round(2)
)

print("\nPreventivas com chave de porta:")
print(
    preventiva["chave_porta"]
    .notna()
    .sum()
)

Granularidade da preventiva:
granularidade_localizacao
plataforma         313
estacao            173
sem_localizacao     83
Name: count, dtype: int64

Percentuais:
granularidade_localizacao
plataforma         55.01
estacao            30.40
sem_localizacao    14.59
Name: proportion, dtype: float64

Preventivas com chave de porta:
0

In [29]:
display(
    preventiva[
        [
            "local_instalacao_preventiva",
            "estacao",
            "plataforma",
            "porta",
            "granularidade_localizacao",
            "chave_porta"
        ]
    ].head(30)
)

,local_instalacao_preventiva,estacao,plataforma,porta,granularidade_localizacao,chave_porta
0,SP04-6-PSD-PTA,PTA,<NA>,<NA>,estacao,<NA>
1,SP04-6-PSD-FAL,FAL,<NA>,<NA>,estacao,<NA>
2,SP04-6-PSD-PIN,PIN,<NA>,<NA>,estacao,<NA>
3,SP04-6-PSD-BUT,BUT,<NA>,<NA>,estacao,<NA>
4,SP04-6-PSD-VSO-PLT1,VSO,1,<NA>,plataforma,<NA>
5,SP04-6-PSD-PTA,PTA,<NA>,<NA>,estacao,<NA>
6,SP04-6-PSD-FAL,FAL,<NA>,<NA>,estacao,<NA>
7,SP04-6-PSD-PIN,PIN,<NA>,<NA>,estacao,<NA>
8,SP04-6-PSD-BUT,BUT,<NA>,<NA>,estacao,<NA>
9,SP04-6-PSD-MBI-PLT2,MBI,2,<NA>,plataforma,<NA>
10,SP04-6-PSD-MBI-PLT1,MBI,1,<NA>,plataforma,<NA>
11,SP04-6-PSD-PTA-PLT1,PTA,1,<NA>,plataforma,<NA>
12,SP04-6-PSD-PTA-PLT2,PTA,2,<NA>,plataforma,<NA>
13,SP04-6-PSD-FAL-PLT1,FAL,1,<NA>,plataforma,<NA>
14,SP04-6-PSD-FAL-PLT2,FAL,2,<NA>,plataforma,<NA>
15,SP04-6-PSD-PTA,PTA,<NA>,<NA>,estacao,<NA>
16,SP04-6-PSD-FAL,FAL,<NA>,<NA>,estacao,<NA>
17,SP04-6-PSD-PVS,PVS,<NA>,<NA>,estacao,<NA>
18,SP04-6-PSD-PIN,PIN,<NA>,<NA>,estacao,<NA>
19,SP04-6-PSD-BUT,BUT,<NA>,<NA>,estacao,<NA>
20,SP04-6-PSD-FRA-PLT2,FRA,2,<NA>,plataforma,<NA>
21,SP04-6-PSD-FRA-PLT1,FRA,1,<NA>,plataforma,<NA>
22,SP04-6-PSD-REP-PLT2,REP,2,<NA>,plataforma,<NA>
23,SP04-6-PSD-REP-PLT1,REP,1,<NA>,plataforma,<NA>
24,SP04-6-PSD-PTA,PTA,<NA>,<NA>,estacao,<NA>
25,SP04-6-PSD-FAL,FAL,<NA>,<NA>,estacao,<NA>
26,SP04-6-PSD-HIG-PLT2,HIG,2,<NA>,plataforma,<NA>
27,SP04-6-PSD-HIG-PLT1,HIG,1,<NA>,plataforma,<NA>
28,SP04-6-PSD-PIN,PIN,<NA>,<NA>,estacao,<NA>
29,SP04-6-PSD-BUT,BUT,<NA>,<NA>,estacao,<NA>

In [30]:
# ==========================================
# CHAVES HIERÁRQUICAS DE LOCALIZAÇÃO
# ==========================================

# ---------- ALARMES ----------

alarmes["chave_estacao"] = alarmes["estacao"]

alarmes["chave_plataforma"] = (
    alarmes["estacao"].astype("string")
    + "_P"
    + alarmes["plataforma"].astype("string")
)

alarmes.loc[
    alarmes[["estacao", "plataforma"]].isna().any(axis=1),
    "chave_plataforma"
] = pd.NA


# ---------- EMERGENCIAL ----------

emergencial["chave_estacao"] = emergencial["estacao"]

emergencial["chave_plataforma"] = (
    emergencial["estacao"].astype("string")
    + "_P"
    + emergencial["plataforma"].astype("string")
)

emergencial.loc[
    emergencial[["estacao", "plataforma"]].isna().any(axis=1),
    "chave_plataforma"
] = pd.NA


# ---------- PROGRAMADA ----------

programada["chave_estacao"] = programada["estacao"]

programada["chave_plataforma"] = (
    programada["estacao"].astype("string")
    + "_P"
    + programada["plataforma"].astype("string")
)

programada.loc[
    programada[["estacao", "plataforma"]].isna().any(axis=1),
    "chave_plataforma"
] = pd.NA


# ---------- PREVENTIVA ----------

preventiva["chave_estacao"] = preventiva["estacao"]

preventiva["chave_plataforma"] = (
    preventiva["estacao"].astype("string")
    + "_P"
    + preventiva["plataforma"].astype("string")
)

preventiva.loc[
    preventiva[["estacao", "plataforma"]].isna().any(axis=1),
    "chave_plataforma"
] = pd.NA

In [31]:
print("ALARMES")
print("Estação:", alarmes["chave_estacao"].notna().sum())
print("Plataforma:", alarmes["chave_plataforma"].notna().sum())
print("Porta:", alarmes["chave_porta"].notna().sum())

print("\nEMERGENCIAL")
print("Estação:", emergencial["chave_estacao"].notna().sum())
print("Plataforma:", emergencial["chave_plataforma"].notna().sum())
print("Porta:", emergencial["chave_porta"].notna().sum())

print("\nPROGRAMADA")
print("Estação:", programada["chave_estacao"].notna().sum())
print("Plataforma:", programada["chave_plataforma"].notna().sum())
print("Porta:", programada["chave_porta"].notna().sum())

print("\nPREVENTIVA")
print("Estação:", preventiva["chave_estacao"].notna().sum())
print("Plataforma:", preventiva["chave_plataforma"].notna().sum())
print("Porta:", preventiva["chave_porta"].notna().sum())

ALARMES
Estação: 1039871
Plataforma: 1039685
Porta: 1039685

EMERGENCIAL
Estação: 10543
Plataforma: 10297
Porta: 9357

PROGRAMADA
Estação: 1163
Plataforma: 1083
Porta: 1010

PREVENTIVA
Estação: 486
Plataforma: 313
Porta: 0

In [32]:
# ==========================================
# UNIVERSO DE PORTAS
# ==========================================

portas = (
    alarmes[
        ["estacao", "plataforma", "porta", "chave_porta"]
    ]
    .dropna(subset=["chave_porta"])
    .drop_duplicates()
    .sort_values(
        ["estacao", "plataforma", "porta"]
    )
    .reset_index(drop=True)
)

print("Quantidade de portas distintas:")
print(len(portas))

print("\nPortas por estação:")
print(
    portas["estacao"]
    .value_counts()
    .sort_index()
)

display(portas.head(20))

Quantidade de portas distintas:
518

Portas por estação:
estacao
BUT    48
FAL    48
FRA    48
FRE    38
HIG    48
LUZ    48
MBI    48
PIN    48
PTA    48
REP    48
VSO    48
Name: count, dtype: Int64

   estacao plataforma porta chave_porta
0      BUT          1    01  BUT_P1_D01
1      BUT          1    02  BUT_P1_D02
2      BUT          1    03  BUT_P1_D03
3      BUT          1    04  BUT_P1_D04
4      BUT          1    05  BUT_P1_D05
5      BUT          1    06  BUT_P1_D06
6      BUT          1    07  BUT_P1_D07
7      BUT          1    08  BUT_P1_D08
8      BUT          1    09  BUT_P1_D09
9      BUT          1    10  BUT_P1_D10
10     BUT          1    11  BUT_P1_D11
11     BUT          1    12  BUT_P1_D12
12     BUT          1    13  BUT_P1_D13
13     BUT          1    14  BUT_P1_D14
14     BUT          1    15  BUT_P1_D15
15     BUT          1    16  BUT_P1_D16
16     BUT          1    17  BUT_P1_D17
17     BUT          1    18  BUT_P1_D18
18     BUT          1    19  BUT_P1_D19
19     BUT          1    20  BUT_P1_D20

In [33]:
datas_modelagem = pd.DataFrame({
    "data": pd.date_range(
        start=inicio_modelagem.normalize(),
        end=fim_modelagem.normalize(),
        freq="D"
    )
})

print("Quantidade de dias:")
print(len(datas_modelagem))

print(
    datas_modelagem["data"].min(),
    "→",
    datas_modelagem["data"].max()
)

Quantidade de dias:
1039
2023-02-27 00:00:00 → 2025-12-31 00:00:00

In [34]:
# ==========================================
# BASE DIÁRIA PORTA × DATA
# ==========================================

portas["join_key"] = 1
datas_modelagem["join_key"] = 1

base_modelo = (
    portas
    .merge(
        datas_modelagem,
        on="join_key"
    )
    .drop(columns="join_key")
)

portas = portas.drop(columns="join_key")
datas_modelagem = datas_modelagem.drop(columns="join_key")

base_modelo = base_modelo[
    [
        "data",
        "estacao",
        "plataforma",
        "porta",
        "chave_porta"
    ]
].sort_values(
    ["chave_porta", "data"]
).reset_index(drop=True)

print("Formato da base:")
print(base_modelo.shape)

display(base_modelo.head(20))

Formato da base:
(538202, 5)

         data estacao plataforma porta chave_porta
0  2023-02-27     BUT          1    01  BUT_P1_D01
1  2023-02-28     BUT          1    01  BUT_P1_D01
2  2023-03-01     BUT          1    01  BUT_P1_D01
3  2023-03-02     BUT          1    01  BUT_P1_D01
4  2023-03-03     BUT          1    01  BUT_P1_D01
5  2023-03-04     BUT          1    01  BUT_P1_D01
6  2023-03-05     BUT          1    01  BUT_P1_D01
7  2023-03-06     BUT          1    01  BUT_P1_D01
8  2023-03-07     BUT          1    01  BUT_P1_D01
9  2023-03-08     BUT          1    01  BUT_P1_D01
10 2023-03-09     BUT          1    01  BUT_P1_D01
11 2023-03-10     BUT          1    01  BUT_P1_D01
12 2023-03-11     BUT          1    01  BUT_P1_D01
13 2023-03-12     BUT          1    01  BUT_P1_D01
14 2023-03-13     BUT          1    01  BUT_P1_D01
15 2023-03-14     BUT          1    01  BUT_P1_D01
16 2023-03-15     BUT          1    01  BUT_P1_D01
17 2023-03-16     BUT          1    01  BUT_P1_D01
18 2023-03-17     BUT          1    01  BUT_P1_D01
19 2023-03-18     BUT          1    01  BUT_P1_D01

In [35]:
# ==========================================
# EVENTOS EMERGENCIAIS PARA O TARGET
# ==========================================

eventos_emergenciais = (
    emergencial[
        emergencial["elegivel_target"]
        & emergencial["inicio_avaria_datetime_emergencial"].notna()
        & emergencial["chave_porta"].notna()
    ]
    [
        [
            "chave_porta",
            "inicio_avaria_datetime_emergencial"
        ]
    ]
    .drop_duplicates()
    .copy()
)

eventos_emergenciais = eventos_emergenciais.sort_values(
    ["inicio_avaria_datetime_emergencial", "chave_porta"]
).reset_index(drop=True)

print("Eventos emergenciais utilizáveis:")
print(len(eventos_emergenciais))

print("\nPortas diferentes com manutenção emergencial:")
print(eventos_emergenciais["chave_porta"].nunique())

print("\nPeríodo:")
print(eventos_emergenciais["inicio_avaria_datetime_emergencial"].min())
print(eventos_emergenciais["inicio_avaria_datetime_emergencial"].max())

Eventos emergenciais utilizáveis:
9253

Portas diferentes com manutenção emergencial:
524

Período:
2023-01-01 02:39:00
2026-04-01 22:43:00

In [36]:
# ==========================================
# PRÓXIMA MANUTENÇÃO EMERGENCIAL
# ==========================================

base_target = base_modelo.copy()

base_target["data"] = pd.to_datetime(
    base_target["data"]
)

base_target = base_target.sort_values(
    ["data", "chave_porta"]
).reset_index(drop=True)

eventos_emergenciais = eventos_emergenciais.sort_values(
    ["inicio_avaria_datetime_emergencial", "chave_porta"]
).reset_index(drop=True)

base_target = pd.merge_asof(
    base_target,
    eventos_emergenciais,
    left_on="data",
    right_on="inicio_avaria_datetime_emergencial",
    by="chave_porta",
    direction="forward",
    allow_exact_matches=True
)

In [37]:
base_target["dias_ate_emergencial"] = (
    base_target["inicio_avaria_datetime_emergencial"]
    - base_target["data"]
).dt.total_seconds() / 86400

In [38]:
# ==========================================
# TARGET: MANUTENÇÃO EMERGENCIAL EM ATÉ 7 DIAS
# ==========================================

base_target["manutencao_emergencial_7d"] = (
    (base_target["dias_ate_emergencial"] >= 0)
    & (base_target["dias_ate_emergencial"] < 7)
).astype(int)

In [39]:
print("Distribuição do target:")
print(
    base_target["manutencao_emergencial_7d"]
    .value_counts()
)

print("\nPercentual:")
print(
    base_target["manutencao_emergencial_7d"]
    .value_counts(normalize=True)
    .mul(100)
    .round(2)
)

print("\nDias até a emergência nos positivos:")
print(
    base_target.loc[
        base_target["manutencao_emergencial_7d"] == 1,
        "dias_ate_emergencial"
    ].describe()
)

Distribuição do target:
manutencao_emergencial_7d
0    496548
1     41654
Name: count, dtype: int64

Percentual:
manutencao_emergencial_7d
0    92.26
1     7.74
Name: proportion, dtype: float64

Dias até a emergência nos positivos:
count    41654.000000
mean         3.385910
std          2.031515
min          0.000694
25%          1.594022
50%          3.345122
75%          5.234028
max          6.999456
Name: dias_ate_emergencial, dtype: float64

In [40]:
display(
    base_target[
        base_target["manutencao_emergencial_7d"] == 1
    ][
        [
            "data",
            "estacao",
            "plataforma",
            "porta",
            "chave_porta",
            "inicio_avaria_datetime_emergencial",
            "dias_ate_emergencial",
            "manutencao_emergencial_7d"
        ]
    ].head(30)
)

,data,estacao,plataforma,porta,chave_porta,inicio_avaria_datetime_emergencial,dias_ate_emergencial,manutencao_emergencial_7d
24,2023-02-27,BUT,2,01,BUT_P2_D01,2023-03-04 14:34:00,5.606944,1
49,2023-02-27,FAL,1,02,FAL_P1_D02,2023-03-01 13:00:00,2.541667,1
60,2023-02-27,FAL,1,13,FAL_P1_D13,2023-02-27 18:02:00,0.751389,1
93,2023-02-27,FAL,2,22,FAL_P2_D22,2023-03-04 19:31:00,5.813194,1
103,2023-02-27,FRA,1,08,FRA_P1_D08,2023-03-02 14:31:00,3.604861,1
119,2023-02-27,FRA,1,24,FRA_P1_D24,2023-02-28 04:16:00,1.177778,1
135,2023-02-27,FRA,2,16,FRA_P2_D16,2023-03-01 07:28:00,2.311111,1
150,2023-02-27,FRE,1,08,FRE_P1_D08,2023-03-01 21:55:00,2.913194,1
176,2023-02-27,FRE,2,17,FRE_P2_D17,2023-03-05 04:49:00,6.200694,1
196,2023-02-27,HIG,1,15,HIG_P1_D15,2023-03-05 13:25:00,6.559028,1
220,2023-02-27,HIG,2,15,HIG_P2_D15,2023-03-02 09:25:00,3.392361,1
278,2023-02-27,MBI,1,01,MBI_P1_D01,2023-03-01 03:56:00,2.163889,1
323,2023-02-27,MBI,2,22,MBI_P2_D22,2023-03-03 12:03:00,4.502083,1
355,2023-02-27,PIN,2,06,PIN_P2_D06,2023-03-03 17:08:00,4.713889,1
377,2023-02-27,PTA,1,04,PTA_P1_D04,2023-02-27 04:10:00,0.173611,1
379,2023-02-27,PTA,1,06,PTA_P1_D06,2023-03-02 06:06:00,3.254167,1
385,2023-02-27,PTA,1,12,PTA_P1_D12,2023-03-01 19:18:00,2.804167,1
423,2023-02-27,REP,1,02,REP_P1_D02,2023-02-28 23:34:00,1.981944,1
432,2023-02-27,REP,1,11,REP_P1_D11,2023-02-27 19:15:00,0.802083,1
438,2023-02-27,REP,1,17,REP_P1_D17,2023-03-04 09:42:00,5.404167,1
444,2023-02-27,REP,1,23,REP_P1_D23,2023-02-28 09:00:00,1.375000,1
500,2023-02-27,VSO,2,07,VSO_P2_D07,2023-03-05 23:52:00,6.994444,1
501,2023-02-27,VSO,2,08,VSO_P2_D08,2023-03-03 07:45:00,4.322917,1
508,2023-02-27,VSO,2,15,VSO_P2_D15,2023-03-01 07:05:00,2.295139,1
509,2023-02-27,VSO,2,16,VSO_P2_D16,2023-02-27 07:05:00,0.295139,1
542,2023-02-28,BUT,2,01,BUT_P2_D01,2023-03-04 14:34:00,4.606944,1
567,2023-02-28,FAL,1,02,FAL_P1_D02,2023-03-01 13:00:00,1.541667,1
578,2023-02-28,FAL,1,13,FAL_P1_D13,2023-02-28 13:55:00,0.579861,1
611,2023-02-28,FAL,2,22,FAL_P2_D22,2023-03-04 19:31:00,4.813194,1
621,2023-02-28,FRA,1,08,FRA_P1_D08,2023-03-02 14:31:00,2.604861,1

In [41]:
print("Distribuição de falha_flag na ZM01:")

print(
    emergencial[
        "falha_flag_emergencial"
    ].value_counts(dropna=False)
)

print("\nPercentuais:")

print(
    emergencial[
        "falha_flag_emergencial"
    ]
    .value_counts(
        normalize=True,
        dropna=False
    )
    .mul(100)
    .round(2)
)

Distribuição de falha_flag na ZM01:
falha_flag_emergencial
False    7150
True     3393
Name: count, dtype: int64

Percentuais:
falha_flag_emergencial
False    67.82
True     32.18
Name: proportion, dtype: float64

In [42]:
print("ZM01 no nível de porta:")

print(
    emergencial.loc[
        emergencial["elegivel_target"],
        "falha_flag_emergencial"
    ].value_counts(dropna=False)
)

print("\nPercentuais:")

print(
    emergencial.loc[
        emergencial["elegivel_target"],
        "falha_flag_emergencial"
    ]
    .value_counts(
        normalize=True,
        dropna=False
    )
    .mul(100)
    .round(2)
)

ZM01 no nível de porta:
falha_flag_emergencial
False    6275
True     3085
Name: count, dtype: int64

Percentuais:
falha_flag_emergencial
False    67.04
True     32.96
Name: proportion, dtype: float64

In [43]:
pd.crosstab(
    emergencial["falha_flag_emergencial"],
    emergencial["indisponivel_flag_emergencial"],
    dropna=False,
    margins=True
)

indisponivel_flag_emergencial  False  True    All
falha_flag_emergencial
False                           2578  4572   7150
True                             993  2400   3393
All                             3571  6972  10543

In [44]:
# ==========================================
# EVENTOS DE FALHA PARA O TARGET
# ==========================================

eventos_falha = (
    emergencial[
        (emergencial["elegivel_target"])
        & (emergencial["falha_flag_emergencial"] == True)
        & (emergencial["inicio_avaria_datetime_emergencial"].notna())
        & (emergencial["chave_porta"].notna())
    ]
    [
        [
            "chave_porta",
            "inicio_avaria_datetime_emergencial"
        ]
    ]
    .drop_duplicates()
    .copy()
)

eventos_falha = eventos_falha.sort_values(
    ["inicio_avaria_datetime_emergencial", "chave_porta"]
).reset_index(drop=True)

print("Eventos de falha utilizáveis:")
print(len(eventos_falha))

print("\nPortas que apresentaram pelo menos uma falha:")
print(eventos_falha["chave_porta"].nunique())

print("\nPeríodo:")
print(eventos_falha["inicio_avaria_datetime_emergencial"].min())
print(eventos_falha["inicio_avaria_datetime_emergencial"].max())

Eventos de falha utilizáveis:
3057

Portas que apresentaram pelo menos uma falha:
491

Período:
2023-01-01 02:39:00
2026-04-01 22:43:00

In [45]:
# ==========================================
# ENCONTRAR A PRÓXIMA FALHA DA PORTA
# ==========================================

base_target = base_modelo.copy()

base_target["data"] = pd.to_datetime(
    base_target["data"]
)

base_target = base_target.sort_values(
    ["data", "chave_porta"]
).reset_index(drop=True)

eventos_falha = eventos_falha.sort_values(
    ["inicio_avaria_datetime_emergencial", "chave_porta"]
).reset_index(drop=True)

base_target = pd.merge_asof(
    base_target,
    eventos_falha,
    left_on="data",
    right_on="inicio_avaria_datetime_emergencial",
    by="chave_porta",
    direction="forward",
    allow_exact_matches=True
)

In [46]:
base_target["dias_ate_falha"] = (
    base_target["inicio_avaria_datetime_emergencial"]
    - base_target["data"]
).dt.total_seconds() / 86400

In [47]:
# ==========================================
# TARGET FINAL
# FALHA EMERGENCIAL NOS PRÓXIMOS 7 DIAS
# ==========================================

base_target["falha_emergencial_7d"] = (
    (base_target["dias_ate_falha"] >= 0)
    & (base_target["dias_ate_falha"] < 7)
).astype(int)

In [48]:
print("Distribuição do target:")
print(
    base_target["falha_emergencial_7d"]
    .value_counts()
)

print("\nPercentual:")
print(
    base_target["falha_emergencial_7d"]
    .value_counts(normalize=True)
    .mul(100)
    .round(2)
)

print("\nDias até a falha nos positivos:")
print(
    base_target.loc[
        base_target["falha_emergencial_7d"] == 1,
        "dias_ate_falha"
    ].describe()
)

Distribuição do target:
falha_emergencial_7d
0    522753
1     15449
Name: count, dtype: int64

Percentual:
falha_emergencial_7d
0    97.13
1     2.87
Name: proportion, dtype: float64

Dias até a falha nos positivos:
count    15449.000000
mean         3.458805
std          2.023054
min          0.001389
25%          1.662674
50%          3.409722
75%          5.284722
max          6.999456
Name: dias_ate_falha, dtype: float64

In [49]:
# ==========================================
# FEATURES DE HISTÓRICO DE ALARMES
# ==========================================

# Data do alarme
alarmes["data"] = (
    pd.to_datetime(
        alarmes["horario_alarme"],
        errors="coerce"
    )
    .dt.normalize()
)

# Considerar somente alarmes com porta identificada
alarmes_porta = alarmes[
    alarmes["chave_porta"].notna()
    & alarmes["data"].notna()
].copy()

# Quantidade de alarmes por porta e dia
alarmes_diarios = (
    alarmes_porta
    .groupby(
        ["chave_porta", "data"]
    )
    .agg(
        qtd_alarmes_dia=(
            "tipo_alarme",
            "count"
        )
    )
    .reset_index()
)

display(alarmes_diarios.head())

  chave_porta       data  qtd_alarmes_dia
0  BUT_P1_D01 2024-01-21              583
1  BUT_P1_D01 2024-04-04                4
2  BUT_P1_D01 2024-04-09                2
3  BUT_P1_D01 2024-04-13              520
4  BUT_P1_D01 2024-05-23              460

In [50]:
base_features = base_target.merge(
    alarmes_diarios,
    on=["chave_porta", "data"],
    how="left"
)

# Dias sem alarmes = 0
base_features["qtd_alarmes_dia"] = (
    base_features["qtd_alarmes_dia"]
    .fillna(0)
    .astype(int)
)

base_features = base_features.sort_values(
    ["chave_porta", "data"]
).reset_index(drop=True)

In [51]:
# ==========================================
# JANELAS TEMPORAIS
# ==========================================

base_features["qtd_alarmes_1d"] = (
    base_features
    .groupby("chave_porta")["qtd_alarmes_dia"]
    .transform(
        lambda x: x.shift(1).rolling(
            window=1,
            min_periods=1
        ).sum()
    )
)

base_features["qtd_alarmes_3d"] = (
    base_features
    .groupby("chave_porta")["qtd_alarmes_dia"]
    .transform(
        lambda x: x.shift(1).rolling(
            window=3,
            min_periods=1
        ).sum()
    )
)

base_features["qtd_alarmes_7d"] = (
    base_features
    .groupby("chave_porta")["qtd_alarmes_dia"]
    .transform(
        lambda x: x.shift(1).rolling(
            window=7,
            min_periods=1
        ).sum()
    )
)

base_features["qtd_alarmes_30d"] = (
    base_features
    .groupby("chave_porta")["qtd_alarmes_dia"]
    .transform(
        lambda x: x.shift(1).rolling(
            window=30,
            min_periods=1
        ).sum()
    )
)

In [52]:
display(
    base_features[
        [
            "data",
            "chave_porta",
            "qtd_alarmes_dia",
            "qtd_alarmes_1d",
            "qtd_alarmes_3d",
            "qtd_alarmes_7d",
            "qtd_alarmes_30d",
            "falha_emergencial_7d"
        ]
    ].head(80)
)

,data,chave_porta,qtd_alarmes_dia,qtd_alarmes_1d,qtd_alarmes_3d,qtd_alarmes_7d,qtd_alarmes_30d,falha_emergencial_7d
0,2023-02-27,BUT_P1_D01,0,NaN,NaN,NaN,NaN,0
1,2023-02-28,BUT_P1_D01,0,0.0,0.0,0.0,0.0,0
2,2023-03-01,BUT_P1_D01,0,0.0,0.0,0.0,0.0,0
3,2023-03-02,BUT_P1_D01,0,0.0,0.0,0.0,0.0,0
4,2023-03-03,BUT_P1_D01,0,0.0,0.0,0.0,0.0,0
...,...,...,...,...,...,...,...,...
75,2023-05-13,BUT_P1_D01,0,0.0,0.0,0.0,0.0,0
76,2023-05-14,BUT_P1_D01,0,0.0,0.0,0.0,0.0,0
77,2023-05-15,BUT_P1_D01,0,0.0,0.0,0.0,0.0,0
78,2023-05-16,BUT_P1_D01,0,0.0,0.0,0.0,0.0,0
79,2023-05-17,BUT_P1_D01,0,0.0,0.0,0.0,0.0,0

In [53]:
print(
    base_features[
        [
            "qtd_alarmes_1d",
            "qtd_alarmes_3d",
            "qtd_alarmes_7d",
            "qtd_alarmes_30d"
        ]
    ].describe()
)

       qtd_alarmes_1d  qtd_alarmes_3d  qtd_alarmes_7d  qtd_alarmes_30d
count   537684.000000   537684.000000   537684.000000    537684.000000
mean         1.932377        5.791831       13.489745        57.432228
std         31.641211       56.801406       90.246222       207.890617
min          0.000000        0.000000        0.000000         0.000000
25%          0.000000        0.000000        0.000000         0.000000
50%          0.000000        0.000000        0.000000         0.000000
75%          0.000000        0.000000        2.000000        43.000000
max       5668.000000     5668.000000     5674.000000      5674.000000

In [54]:
# Maiores quantidades de alarmes registrados por uma porta em um dia
top_alarmes_dia = (
    alarmes_diarios
    .sort_values(
        "qtd_alarmes_dia",
        ascending=False
    )
    .head(40)
)

display(top_alarmes_dia)

     chave_porta       data  qtd_alarmes_dia
5711  FRA_P1_D03 2024-05-29             5668
7079  FRA_P1_D19 2024-05-13             4990
7136  FRA_P1_D21 2024-05-09             4890
5768  FRA_P1_D04 2024-08-02             3001
7221  FRA_P1_D22 2024-06-28             2990
7098  FRA_P1_D20 2024-08-17             2958
6478  FRA_P1_D12 2024-08-27             2903
7222  FRA_P1_D22 2024-10-01             2848
5860  FRA_P1_D06 2024-08-03             2739
6975  FRA_P1_D17 2024-09-04             2685
9250  FRA_P2_D22 2024-08-04             2620
7440  FRA_P2_D02 2024-09-11             2573
7293  FRA_P1_D24 2024-08-01             2524
5813  FRA_P1_D05 2024-08-01             2509
5581  FRA_P1_D01 2024-08-01             2501
7718  FRA_P2_D06 2024-09-18             2490
8731  FRA_P2_D15 2024-08-10             2487
9227  FRA_P2_D21 2024-09-07             2486
6291  FRA_P1_D10 2024-09-11             2480
7255  FRA_P1_D23 2024-08-03             2444
6048  FRA_P1_D08 2024-10-01             2432
6137  FRA_P1_D09 2024-08-01             2431
7664  FRA_P2_D05 2024-07-18             2431
6542  FRA_P1_D13 2024-08-12             2416
8367  FRA_P2_D11 2024-08-25             2403
6340  FRA_P1_D11 2024-08-29             2402
8762  FRA_P2_D16 2024-09-07             2382
7056  FRA_P1_D18 2024-09-02             2350
7917  FRA_P2_D08 2024-09-03             2347
8798  FRA_P2_D17 2024-09-12             2264
5940  FRA_P1_D07 2024-09-11             2250
6883  FRA_P1_D16 2024-09-14             2221
7985  FRA_P2_D09 2024-10-01             2116
9423  FRA_P2_D24 2024-07-24             2113
8686  FRA_P2_D14 2024-09-22             2018
8488  FRA_P2_D12 2024-09-18             2003
9177  FRA_P2_D20 2024-09-18             1983
7853  FRA_P2_D07 2024-09-22             1969
7616  FRA_P2_D04 2024-09-26             1955
8615  FRA_P2_D13 2024-09-20             1955

In [55]:
# Estatísticas percentis para entender a cauda da distribuição
print(
    alarmes_diarios["qtd_alarmes_dia"]
    .quantile([
        0.90,
        0.95,
        0.99,
        0.995,
        0.999,
        1.0
    ])
)

0.900      38.000
0.950      78.000
0.990     333.360
0.995     537.840
0.999    1671.472
1.000    5668.000
Name: qtd_alarmes_dia, dtype: float64

In [56]:
top_portas_datas = (
    top_alarmes_dia[
        ["chave_porta", "data"]
    ]
)

detalhes_top = alarmes_porta.merge(
    top_portas_datas,
    on=["chave_porta", "data"],
    how="inner"
)

print(
    detalhes_top[
        [
            "chave_porta",
            "data",
            "tipo_alarme"
        ]
    ]
    .value_counts()
    .head(50)
)

chave_porta  data        tipo_alarme
FRA_P1_D03   2024-05-29  STS            762
                         FO             718
FRA_P1_D19   2024-05-13  CSD            716
                         CA             714
                         OBS            712
                         FC             712
                         FO             712
                         LSD            712
                         OA             712
FRA_P1_D21   2024-05-09  OBS            700
                         FC             700
FRA_P1_D03   2024-05-29  OBS            698
                         CA             698
                         CSD            698
                         FC             698
                         LSD            698
                         OA             698
FRA_P1_D21   2024-05-09  CA             698
                         CSD            698
                         FO             698
                         LSD            698
                         OA             698
FRA_P1_D12   2024-08-27  STS            498
FRA_P1_D04   2024-08-02  STS            402
FRA_P1_D22   2024-06-28  STS            398
                         FO             398
FRA_P2_D06   2024-09-18  STS            397
FRA_P1_D06   2024-08-03  OBS            392
                         FC             392
                         CA             391
                         CSD            391
                         FO             391
                         LSD            391
                         OA             391
FRA_P2_D22   2024-08-04  CA             376
                         OBS            374
FRA_P1_D20   2024-08-17  STS            374
FRA_P2_D22   2024-08-04  CSD            374
                         FC             374
                         FO             374
                         LSD            374
                         OA             374
FRA_P1_D05   2024-08-01  LSD            373
FRA_P1_D04   2024-08-02  OBS            372
                         FC             372
                         FO             372
                         CA             371
                         CSD            371
                         OA             371
FRA_P2_D02   2024-09-11  LSD            371
Name: count, dtype: int64

In [57]:
# ==========================================
# INVESTIGAÇÃO DO MAIOR PICO DE ALARMES
# ==========================================

caso_extremo = alarmes_porta[
    (alarmes_porta["chave_porta"] == "FRA_P1_D03")
    & (alarmes_porta["data"] == pd.Timestamp("2024-05-29"))
].copy()

caso_extremo = caso_extremo.sort_values(
    "horario_alarme"
)

print("Total de registros:")
print(len(caso_extremo))

print("\nTipos de alarme:")
print(
    caso_extremo["tipo_alarme"]
    .value_counts()
)

print("\nPrimeiros registros:")
display(
    caso_extremo[
        [
            "horario_alarme",
            "tipo_alarme",
            "horario_normalizacao_alarme",
            "tag_alarme"
        ]
    ].head(30)
)

Total de registros:
5668

Tipos de alarme:
tipo_alarme
STS    762
FO     718
CA     698
OBS    698
CSD    698
LSD    698
OA     698
FC     698
Name: count, dtype: int64

Primeiros registros:

,horario_alarme,tipo_alarme,horario_normalizacao_alarme,tag_alarme
318810,2024-05-29 09:58:06.187,STS,2024-05-29 09:58:21.187,PSD_P_FRA1_MDU03_STS
220173,2024-05-29 09:58:06.187,STS,2024-05-29 09:58:21.187,PSD_P_FRA1_MDU03_STS
223826,2024-05-29 09:58:06.187,FO,2024-05-29 09:58:21.187,PSD_P_FRA1_PDM03_FO
323753,2024-05-29 09:58:06.187,FO,2024-05-29 09:58:21.187,PSD_P_FRA1_PDM03_FO
318811,2024-05-29 09:58:26.187,STS,2024-05-29 09:58:41.187,PSD_P_FRA1_MDU03_STS
323754,2024-05-29 09:58:26.187,FO,2024-05-29 09:58:41.187,PSD_P_FRA1_PDM03_FO
220174,2024-05-29 09:58:26.187,STS,2024-05-29 09:58:41.187,PSD_P_FRA1_MDU03_STS
223827,2024-05-29 09:58:26.187,FO,2024-05-29 09:58:41.187,PSD_P_FRA1_PDM03_FO
223828,2024-05-29 09:58:51.187,FO,2024-05-29 09:58:56.203,PSD_P_FRA1_PDM03_FO
220175,2024-05-29 09:58:51.187,STS,2024-05-29 09:58:56.203,PSD_P_FRA1_MDU03_STS
318812,2024-05-29 09:58:51.187,STS,2024-05-29 09:58:56.203,PSD_P_FRA1_MDU03_STS
323755,2024-05-29 09:58:51.187,FO,2024-05-29 09:58:56.203,PSD_P_FRA1_PDM03_FO
318813,2024-05-29 09:59:01.187,STS,2024-05-29 09:59:11.203,PSD_P_FRA1_MDU03_STS
220176,2024-05-29 09:59:01.187,STS,2024-05-29 09:59:11.203,PSD_P_FRA1_MDU03_STS
323756,2024-05-29 09:59:01.187,FO,2024-05-29 09:59:11.203,PSD_P_FRA1_PDM03_FO
223829,2024-05-29 09:59:01.187,FO,2024-05-29 09:59:11.203,PSD_P_FRA1_PDM03_FO
223830,2024-05-29 09:59:16.190,FO,2024-05-29 10:03:46.190,PSD_P_FRA1_PDM03_FO
318814,2024-05-29 09:59:16.190,STS,2024-05-29 10:03:46.190,PSD_P_FRA1_MDU03_STS
220177,2024-05-29 09:59:16.190,STS,2024-05-29 10:03:46.190,PSD_P_FRA1_MDU03_STS
323757,2024-05-29 09:59:16.190,FO,2024-05-29 10:03:46.190,PSD_P_FRA1_PDM03_FO
318815,2024-05-29 10:03:56.190,STS,2024-05-29 10:05:01.190,PSD_P_FRA1_MDU03_STS
223831,2024-05-29 10:03:56.190,FO,2024-05-29 10:05:01.190,PSD_P_FRA1_PDM03_FO
323758,2024-05-29 10:03:56.190,FO,2024-05-29 10:05:01.190,PSD_P_FRA1_PDM03_FO
220178,2024-05-29 10:03:56.190,STS,2024-05-29 10:05:01.190,PSD_P_FRA1_MDU03_STS
223832,2024-05-29 10:05:06.190,FO,2024-05-29 10:05:21.190,PSD_P_FRA1_PDM03_FO
318816,2024-05-29 10:05:06.190,STS,2024-05-29 10:05:21.190,PSD_P_FRA1_MDU03_STS
220179,2024-05-29 10:05:06.190,STS,2024-05-29 10:05:21.190,PSD_P_FRA1_MDU03_STS
323759,2024-05-29 10:05:06.190,FO,2024-05-29 10:05:21.190,PSD_P_FRA1_PDM03_FO
323760,2024-05-29 10:05:41.190,FO,2024-05-29 10:06:01.190,PSD_P_FRA1_PDM03_FO
318817,2024-05-29 10:05:41.190,STS,2024-05-29 10:06:01.190,PSD_P_FRA1_MDU03_STS

In [58]:
duplicados_exatos = caso_extremo.duplicated(
    subset=[
        "chave_porta",
        "horario_alarme",
        "tipo_alarme"
    ],
    keep=False
)

print("Registros envolvidos em duplicatas exatas:")
print(duplicados_exatos.sum())

print("\nPercentual:")
print(
    round(
        duplicados_exatos.mean() * 100,
        2
    ),
    "%"
)

Registros envolvidos em duplicatas exatas:
5668

Percentual:
100.0 %

In [59]:
caso_extremo["segundos_desde_alarme_anterior"] = (
    caso_extremo["horario_alarme"]
    .diff()
    .dt.total_seconds()
)

print(
    caso_extremo[
        "segundos_desde_alarme_anterior"
    ].describe(
        percentiles=[
            0.01,
            0.05,
            0.10,
            0.25,
            0.50,
            0.75,
            0.90,
            0.99
        ]
    )
)

count    5667.000000
mean        0.103230
std         4.147504
min         0.000000
1%          0.000000
5%          0.000000
10%         0.000000
25%         0.000000
50%         0.000000
75%         0.000000
90%         0.000000
99%         0.000000
max       280.000000
Name: segundos_desde_alarme_anterior, dtype: float64

In [60]:
# ==========================================
# VERIFICAÇÃO GLOBAL DE DUPLICATAS
# ==========================================

colunas_evento = [
    "tag_alarme",
    "horario_alarme",
    "tipo_alarme",
    "horario_normalizacao_alarme"
]

duplicados = alarmes.duplicated(
    subset=colunas_evento,
    keep=False
)

print("Total de registros:")
print(len(alarmes))

print("\nRegistros envolvidos em duplicatas:")
print(duplicados.sum())

print("\nPercentual envolvido em duplicatas:")
print(
    round(
        duplicados.mean() * 100,
        2
    ),
    "%"
)

print("\nQuantidade de linhas redundantes:")
print(
    alarmes.duplicated(
        subset=colunas_evento,
        keep="first"
    ).sum()
)

Total de registros:
1039871

Registros envolvidos em duplicatas:
262898

Percentual envolvido em duplicatas:
25.28 %

Quantidade de linhas redundantes:
131449

In [61]:
alarmes_limpos = (
    alarmes
    .drop_duplicates(
        subset=colunas_evento,
        keep="first"
    )
    .copy()
)

print("Antes:", len(alarmes))
print("Depois:", len(alarmes_limpos))
print("Removidos:", len(alarmes) - len(alarmes_limpos))

Antes: 1039871
Depois: 908422
Removidos: 131449

In [62]:
caso_extremo_limpo = alarmes_limpos[
    (alarmes_limpos["chave_porta"] == "FRA_P1_D03")
    & (alarmes_limpos["data"] == pd.Timestamp("2024-05-29"))
]

print(
    caso_extremo_limpo["tipo_alarme"]
    .value_counts()
)

print("\nTotal:")
print(len(caso_extremo_limpo))

tipo_alarme
STS    381
FO     359
OBS    349
CA     349
CSD    349
FC     349
LSD    349
OA     349
Name: count, dtype: int64

Total:
2834

In [63]:
alarmes_porta = alarmes_limpos[
    alarmes_limpos["chave_porta"].notna()
    & alarmes_limpos["data"].notna()
].copy()

alarmes_diarios = (
    alarmes_porta
    .groupby(
        ["chave_porta", "data"]
    )
    .agg(
        qtd_alarmes_dia=(
            "tipo_alarme",
            "count"
        )
    )
    .reset_index()
)

In [64]:
caso_extremo_limpo = (
    caso_extremo_limpo
    .sort_values("horario_alarme")
    .copy()
)

caso_extremo_limpo["segundos_desde_alarme_anterior"] = (
    caso_extremo_limpo["horario_alarme"]
    .diff()
    .dt.total_seconds()
)

print(
    caso_extremo_limpo[
        "segundos_desde_alarme_anterior"
    ].describe(
        percentiles=[
            0.01,
            0.05,
            0.10,
            0.25,
            0.50,
            0.75,
            0.90,
            0.95,
            0.99
        ]
    )
)

count    2833.000000
mean        0.206497
std         5.864673
min         0.000000
1%          0.000000
5%          0.000000
10%         0.000000
25%         0.000000
50%         0.000000
75%         0.000000
90%         0.000000
95%         0.000000
99%         0.000000
max       280.000000
Name: segundos_desde_alarme_anterior, dtype: float64

In [65]:
print("Total de alarmes limpos:")
print(len(caso_extremo_limpo))

print("\nHorários de disparo distintos:")
print(
    caso_extremo_limpo[
        "horario_alarme"
    ].nunique()
)

print("\nQuantidade média de alarmes por instante:")
print(
    len(caso_extremo_limpo)
    /
    caso_extremo_limpo["horario_alarme"].nunique()
)

Total de alarmes limpos:
2834

Horários de disparo distintos:
10

Quantidade média de alarmes por instante:
283.4

In [66]:
# Verificar quantos eventos realmente distintos existem
# considerando TAG + horário de disparo

print("Combinações únicas TAG + horário:")
print(
    caso_extremo_limpo[
        ["tag_alarme", "horario_alarme"]
    ]
    .drop_duplicates()
    .shape[0]
)

print("\nQuantidade de registros por TAG + horário:")
print(
    caso_extremo_limpo
    .groupby(
        ["tag_alarme", "horario_alarme"]
    )
    .size()
    .sort_values(ascending=False)
    .head(30)
)

Combinações únicas TAG + horário:
26

Quantidade de registros por TAG + horário:
tag_alarme              horario_alarme
PSD_P_FRA1_MDU03_STS    2024-05-29 10:07:51.193    372
PSD_P_FRA1_PDM03_FO     2024-05-29 10:07:51.193    350
PSD_P_FRA1_PDM03_CA     2024-05-29 10:07:51.193    349
PSD_P_FRA1_PDM03_FC     2024-05-29 10:07:51.193    349
PSD_P_FRA1_PDM03_OA     2024-05-29 10:07:51.193    349
PSD_P_FRA1_PDM03_LSD    2024-05-29 10:07:51.193    349
PSD_FRA_FRA1_PDM03_OBS  2024-05-29 10:07:51.193    349
PSD_P_FRA1_PDM03_CSD    2024-05-29 10:07:51.193    349
PSD_P_FRA1_MDU03_STS    2024-05-29 09:58:26.187      1
                        2024-05-29 09:58:06.187      1
                        2024-05-29 10:06:06.190      1
                        2024-05-29 10:05:41.190      1
                        2024-05-29 10:05:06.190      1
                        2024-05-29 10:03:56.190      1
                        2024-05-29 09:59:16.190      1
                        2024-05-29 09:59:01.187      1
                        2024-05-29 09:58:51.187      1
PSD_P_FRA1_PDM03_FO     2024-05-29 09:58:06.187      1
                        2024-05-29 09:59:01.187      1
                        2024-05-29 09:58:51.187      1
                        2024-05-29 09:58:26.187      1
                        2024-05-29 09:59:16.190      1
                        2024-05-29 10:05:41.190      1
                        2024-05-29 10:05:06.190      1
                        2024-05-29 10:03:56.190      1
                        2024-05-29 10:06:06.190      1
dtype: int64

In [67]:
normalizacoes_por_evento = (
    caso_extremo_limpo
    .groupby(
        ["tag_alarme", "horario_alarme"]
    )
    ["horario_normalizacao_alarme"]
    .nunique()
    .sort_values(ascending=False)
)

print(
    normalizacoes_por_evento.head(30)
)

print("\nEventos com mais de uma normalização:")
print(
    (normalizacoes_por_evento > 1).sum()
)

tag_alarme              horario_alarme
PSD_P_FRA1_MDU03_STS    2024-05-29 10:07:51.193    372
PSD_P_FRA1_PDM03_FO     2024-05-29 10:07:51.193    350
PSD_P_FRA1_PDM03_CA     2024-05-29 10:07:51.193    349
PSD_P_FRA1_PDM03_FC     2024-05-29 10:07:51.193    349
PSD_P_FRA1_PDM03_OA     2024-05-29 10:07:51.193    349
PSD_P_FRA1_PDM03_LSD    2024-05-29 10:07:51.193    349
PSD_FRA_FRA1_PDM03_OBS  2024-05-29 10:07:51.193    349
PSD_P_FRA1_PDM03_CSD    2024-05-29 10:07:51.193    349
PSD_P_FRA1_MDU03_STS    2024-05-29 09:58:26.187      1
                        2024-05-29 09:58:06.187      1
                        2024-05-29 10:06:06.190      1
                        2024-05-29 10:05:41.190      1
                        2024-05-29 10:05:06.190      1
                        2024-05-29 10:03:56.190      1
                        2024-05-29 09:59:16.190      1
                        2024-05-29 09:59:01.187      1
                        2024-05-29 09:58:51.187      1
PSD_P_FRA1_PDM03_FO     2024-05-29 09:58:06.187      1
                        2024-05-29 09:59:01.187      1
                        2024-05-29 09:58:51.187      1
                        2024-05-29 09:58:26.187      1
                        2024-05-29 09:59:16.190      1
                        2024-05-29 10:05:41.190      1
                        2024-05-29 10:05:06.190      1
                        2024-05-29 10:03:56.190      1
                        2024-05-29 10:06:06.190      1
Name: horario_normalizacao_alarme, dtype: int64

Eventos com mais de uma normalização:
8

In [68]:
# ==========================================
# BASE DE EVENTOS ÚNICOS DE ALARME
# ==========================================

alarmes_eventos = (
    alarmes
    .sort_values("horario_alarme")
    .drop_duplicates(
        subset=[
            "tag_alarme",
            "horario_alarme"
        ],
        keep="first"
    )
    .copy()
)

print("Registros originais:")
print(len(alarmes))

print("\nEventos únicos:")
print(len(alarmes_eventos))

print("\nRegistros redundantes removidos:")
print(
    len(alarmes)
    - len(alarmes_eventos)
)

print("\nPercentual de redução:")
print(
    round(
        (1 - len(alarmes_eventos) / len(alarmes)) * 100,
        2
    ),
    "%"
)

Registros originais:
1039871

Eventos únicos:
345454

Registros redundantes removidos:
694417

Percentual de redução:
66.78 %

In [69]:
caso_extremo_eventos = alarmes_eventos[
    (alarmes_eventos["chave_porta"] == "FRA_P1_D03")
    & (
        alarmes_eventos["data"]
        == pd.Timestamp("2024-05-29")
    )
]

print("Eventos únicos no dia:")
print(len(caso_extremo_eventos))

print("\nPor tipo:")
print(
    caso_extremo_eventos[
        "tipo_alarme"
    ].value_counts()
)

Eventos únicos no dia:
26

Por tipo:
tipo_alarme
FO     10
STS    10
CA      1
FC      1
OA      1
LSD     1
OBS     1
CSD     1
Name: count, dtype: int64

In [70]:
alarmes_porta = alarmes_eventos[
    alarmes_eventos["chave_porta"].notna()
    & alarmes_eventos["data"].notna()
].copy()

alarmes_diarios = (
    alarmes_porta
    .groupby(
        ["chave_porta", "data"]
    )
    .agg(
        qtd_alarmes_dia=(
            "tipo_alarme",
            "count"
        )
    )
    .reset_index()
)

In [71]:
display(
    alarmes_diarios
    .sort_values(
        "qtd_alarmes_dia",
        ascending=False
    )
    .head(30)
)

      chave_porta       data  qtd_alarmes_dia
32454  PTA_P1_D03 2024-04-24              694
28265  PIN_P1_D24 2025-02-17              622
13447  HIG_P2_D10 2024-11-27              612
24948  MBI_P2_D09 2025-05-15              516
43577  VSO_P1_D01 2025-02-12              500
209    BUT_P1_D07 2025-12-09              474
27495  PIN_P1_D14 2024-09-24              466
27494  PIN_P1_D14 2024-09-23              458
43582  VSO_P1_D01 2025-02-17              454
25957  MBI_P2_D24 2025-12-27              439
4711   FAL_P2_D09 2024-12-26              437
35769  REP_P1_D01 2025-10-01              436
6864   FRA_P1_D16 2024-01-30              420
7973   FRA_P2_D09 2024-06-18              410
25904  MBI_P2_D24 2024-11-24              406
13448  HIG_P2_D10 2024-11-28              392
12246  HIG_P2_D02 2025-07-16              375
32463  PTA_P1_D03 2024-06-22              368
1287   BUT_P1_D21 2025-12-10              366
24425  MBI_P1_D22 2025-12-11              362
23339  MBI_P1_D01 2025-10-29              360
45265  VSO_P2_D15 2024-10-31              356
7974   FRA_P2_D09 2024-06-19              354
45271  VSO_P2_D15 2024-11-06              338
25989  PIN_P1_D02 2024-06-03              329
25092  MBI_P2_D13 2025-12-26              326
15224  HIG_P2_D17 2024-09-20              323
45270  VSO_P2_D15 2024-11-05              314
45269  VSO_P2_D15 2024-11-04              309
7972   FRA_P2_D09 2024-06-17              308

In [72]:
# ==========================================
# RECONSTRUÇÃO DAS FEATURES DE ALARMES
# USANDO EVENTOS ÚNICOS
# ==========================================

alarmes_porta = alarmes_eventos[
    alarmes_eventos["chave_porta"].notna()
    & alarmes_eventos["data"].notna()
].copy()

# Quantidade de eventos únicos por porta e dia
alarmes_diarios = (
    alarmes_porta
    .groupby(["chave_porta", "data"])
    .agg(
        qtd_alarmes_dia=("tipo_alarme", "count")
    )
    .reset_index()
)

# Recomeçar a base de features a partir do target
base_features = base_target.merge(
    alarmes_diarios,
    on=["chave_porta", "data"],
    how="left"
)

base_features["qtd_alarmes_dia"] = (
    base_features["qtd_alarmes_dia"]
    .fillna(0)
    .astype(int)
)

base_features = base_features.sort_values(
    ["chave_porta", "data"]
).reset_index(drop=True)

In [73]:
base_features["qtd_alarmes_1d"] = (
    base_features
    .groupby("chave_porta")["qtd_alarmes_dia"]
    .transform(
        lambda x: x.shift(1).rolling(1, min_periods=1).sum()
    )
)

base_features["qtd_alarmes_3d"] = (
    base_features
    .groupby("chave_porta")["qtd_alarmes_dia"]
    .transform(
        lambda x: x.shift(1).rolling(3, min_periods=1).sum()
    )
)

base_features["qtd_alarmes_7d"] = (
    base_features
    .groupby("chave_porta")["qtd_alarmes_dia"]
    .transform(
        lambda x: x.shift(1).rolling(7, min_periods=1).sum()
    )
)

base_features["qtd_alarmes_30d"] = (
    base_features
    .groupby("chave_porta")["qtd_alarmes_dia"]
    .transform(
        lambda x: x.shift(1).rolling(30, min_periods=1).sum()
    )
)

In [74]:
data_inicio_modelo_efetivo = (
    inicio_modelagem.normalize()
    + pd.Timedelta(days=30)
)

base_features = base_features[
    base_features["data"] >= data_inicio_modelo_efetivo
].copy()

base_features = base_features.reset_index(drop=True)

In [75]:
print(
    base_features[
        [
            "qtd_alarmes_1d",
            "qtd_alarmes_3d",
            "qtd_alarmes_7d",
            "qtd_alarmes_30d"
        ]
    ].describe()
)

print("\nValores ausentes:")
print(
    base_features[
        [
            "qtd_alarmes_1d",
            "qtd_alarmes_3d",
            "qtd_alarmes_7d",
            "qtd_alarmes_30d"
        ]
    ].isna().sum()
)

       qtd_alarmes_1d  qtd_alarmes_3d  qtd_alarmes_7d  qtd_alarmes_30d
count   522662.000000   522662.000000   522662.000000    522662.000000
mean         0.659357        1.973700        4.582221        19.284861
std          6.011014       14.472107       27.896997        80.835201
min          0.000000        0.000000        0.000000         0.000000
25%          0.000000        0.000000        0.000000         0.000000
50%          0.000000        0.000000        0.000000         0.000000
75%          0.000000        0.000000        2.000000        16.000000
max        694.000000     1260.000000     1982.000000      4113.000000

Valores ausentes:
qtd_alarmes_1d     0
qtd_alarmes_3d     0
qtd_alarmes_7d     0
qtd_alarmes_30d    0
dtype: int64

In [76]:
print(
    alarmes_eventos["tipo_alarme"]
    .value_counts()
)

tipo_alarme
LSD      65151
FC       55928
FO       55389
OBS      52079
STS      45074
OA       38480
CA       16445
CSD      13500
RCE       3275
VALUE      133
Name: count, dtype: int64

In [77]:
# ==========================================
# QUANTIDADE DIÁRIA POR TIPO DE ALARME
# ==========================================

alarmes_tipo_dia = (
    alarmes_porta
    .groupby(
        [
            "chave_porta",
            "data",
            "tipo_alarme"
        ]
    )
    .size()
    .unstack(fill_value=0)
    .reset_index()
)

display(alarmes_tipo_dia.head())

tipo_alarme chave_porta       data  CA  CSD  FC  FO  LSD  OA  OBS  RCE  STS
0            BUT_P1_D01 2024-01-21   1    1   1   1    1   1    1    0    0
1            BUT_P1_D01 2024-04-04   0    0   1   0    0   0    1    0    0
2            BUT_P1_D01 2024-04-09   0    0   0   0    0   1    0    0    0
3            BUT_P1_D01 2024-04-13   1    1   1   1    1   1    1    0    0
4            BUT_P1_D01 2024-05-23   1    1   1   1    1   1    1    0    1

In [78]:
colunas_tipos = [
    coluna
    for coluna in alarmes_tipo_dia.columns
    if coluna not in ["chave_porta", "data"]
]

alarmes_tipo_dia = alarmes_tipo_dia.rename(
    columns={
        coluna: f"qtd_{coluna.lower()}_dia"
        for coluna in colunas_tipos
    }
)

display(alarmes_tipo_dia.head())

tipo_alarme,chave_porta,data,qtd_ca_dia,qtd_csd_dia,qtd_fc_dia,qtd_fo_dia,qtd_lsd_dia,qtd_oa_dia,qtd_obs_dia,qtd_rce_dia,qtd_sts_dia
0,BUT_P1_D01,2024-01-21,1,1,1,1,1,1,1,0,0
1,BUT_P1_D01,2024-04-04,0,0,1,0,0,0,1,0,0
2,BUT_P1_D01,2024-04-09,0,0,0,0,0,1,0,0,0
3,BUT_P1_D01,2024-04-13,1,1,1,1,1,1,1,0,0
4,BUT_P1_D01,2024-05-23,1,1,1,1,1,1,1,0,1

In [79]:
base_features = base_features.merge(
    alarmes_tipo_dia,
    on=["chave_porta", "data"],
    how="left"
)

colunas_tipo_dia = [
    coluna
    for coluna in base_features.columns
    if coluna.startswith("qtd_")
    and coluna.endswith("_dia")
    and coluna != "qtd_alarmes_dia"
]

base_features[colunas_tipo_dia] = (
    base_features[colunas_tipo_dia]
    .fillna(0)
)

In [80]:
for coluna in colunas_tipo_dia:

    nome_tipo = (
        coluna
        .replace("qtd_", "")
        .replace("_dia", "")
    )

    base_features[f"qtd_{nome_tipo}_7d"] = (
        base_features
        .groupby("chave_porta")[coluna]
        .transform(
            lambda x: x.shift(1)
            .rolling(
                7,
                min_periods=1
            )
            .sum()
        )
    )

    base_features[f"qtd_{nome_tipo}_30d"] = (
        base_features
        .groupby("chave_porta")[coluna]
        .transform(
            lambda x: x.shift(1)
            .rolling(
                30,
                min_periods=1
            )
            .sum()
        )
    )

In [81]:
colunas_features_tipo = [
    coluna
    for coluna in base_features.columns
    if (
        coluna.endswith("_7d")
        or coluna.endswith("_30d")
    )
    and coluna.startswith("qtd_")
]

print(
    base_features[
        colunas_features_tipo
    ].describe().T
)

                    count       mean        std  min  25%  50%   75%     max
qtd_alarmes_7d   522662.0   4.582221  27.896997  0.0  0.0  0.0   2.0  1982.0
qtd_alarmes_30d  522662.0  19.284861  80.835201  0.0  0.0  0.0  16.0  4113.0
qtd_ca_7d        522144.0   0.219570   0.695614  0.0  0.0  0.0   0.0    40.0
qtd_ca_30d       522144.0   0.930992   1.831848  0.0  0.0  0.0   1.0    49.0
qtd_csd_7d       522144.0   0.180299   0.605166  0.0  0.0  0.0   0.0    40.0
qtd_csd_30d      522144.0   0.766187   1.627270  0.0  0.0  0.0   1.0    48.0
qtd_fc_7d        522144.0   0.746890   2.580135  0.0  0.0  0.0   0.0   308.0
qtd_fc_30d       522144.0   3.173852   8.871761  0.0  0.0  0.0   2.0   475.0
qtd_fo_7d        522144.0   0.732294  10.942552  0.0  0.0  0.0   0.0   988.0
qtd_fo_30d       522144.0   3.050501  30.272670  0.0  0.0  0.0   1.0  1578.0
qtd_lsd_7d       522144.0   0.860113  13.798228  0.0  0.0  0.0   0.0  1936.0
qtd_lsd_30d      522144.0   3.595951  42.792865  0.0  0.0  0.0   1.0  4097.0
qtd_oa_7d        522144.0   0.513826   5.561154  0.0  0.0  0.0   0.0   502.0
qtd_oa_30d       522144.0   2.181057  13.630438  0.0  0.0  0.0   1.0   570.0
qtd_obs_7d       522144.0   0.695391   2.438997  0.0  0.0  0.0   0.0   308.0
qtd_obs_30d      522144.0   2.954220   8.535610  0.0  0.0  0.0   2.0   475.0
qtd_rce_7d       522144.0   0.043821   0.861583  0.0  0.0  0.0   0.0   190.0
qtd_rce_30d      522144.0   0.186537   2.575352  0.0  0.0  0.0   0.0   222.0
qtd_sts_7d       522144.0   0.594564  10.936702  0.0  0.0  0.0   0.0   988.0
qtd_sts_30d      522144.0   2.464247  30.245100  0.0  0.0  0.0   0.0  1578.0

In [82]:
# ==========================================
# RECONSTRUIR FEATURES POR TIPO DE ALARME
# ANTES DO CORTE DE AQUECIMENTO
# ==========================================

base_features = base_target.merge(
    alarmes_diarios,
    on=["chave_porta", "data"],
    how="left"
)

base_features["qtd_alarmes_dia"] = (
    base_features["qtd_alarmes_dia"]
    .fillna(0)
    .astype(int)
)

base_features = base_features.merge(
    alarmes_tipo_dia,
    on=["chave_porta", "data"],
    how="left"
)

base_features = base_features.sort_values(
    ["chave_porta", "data"]
).reset_index(drop=True)

# Colunas referentes aos tipos de alarme no próprio dia
colunas_tipo_dia = [
    coluna
    for coluna in base_features.columns
    if coluna.startswith("qtd_")
    and coluna.endswith("_dia")
    and coluna != "qtd_alarmes_dia"
]

base_features[colunas_tipo_dia] = (
    base_features[colunas_tipo_dia]
    .fillna(0)
)

In [83]:
for janela in [1, 3, 7, 30]:

    base_features[f"qtd_alarmes_{janela}d"] = (
        base_features
        .groupby("chave_porta")["qtd_alarmes_dia"]
        .transform(
            lambda x: x.shift(1)
            .rolling(
                janela,
                min_periods=1
            )
            .sum()
        )
    )

In [84]:
for coluna in colunas_tipo_dia:

    tipo = (
        coluna
        .replace("qtd_", "")
        .replace("_dia", "")
    )

    for janela in [7, 30]:

        base_features[f"qtd_{tipo}_{janela}d"] = (
            base_features
            .groupby("chave_porta")[coluna]
            .transform(
                lambda x: x.shift(1)
                .rolling(
                    janela,
                    min_periods=1
                )
                .sum()
            )
        )

In [85]:
data_inicio_modelo_efetivo = (
    inicio_modelagem.normalize()
    + pd.Timedelta(days=30)
)

base_features = base_features[
    base_features["data"] >= data_inicio_modelo_efetivo
].copy()

base_features = base_features.reset_index(drop=True)

In [86]:
colunas_historicas = [
    coluna
    for coluna in base_features.columns
    if (
        coluna.startswith("qtd_")
        and (
            coluna.endswith("_1d")
            or coluna.endswith("_3d")
            or coluna.endswith("_7d")
            or coluna.endswith("_30d")
        )
    )
]

print(
    base_features[
        colunas_historicas
    ].isna().sum()
)

qtd_alarmes_1d     0
qtd_alarmes_3d     0
qtd_alarmes_7d     0
qtd_alarmes_30d    0
qtd_ca_7d          0
qtd_ca_30d         0
qtd_csd_7d         0
qtd_csd_30d        0
qtd_fc_7d          0
qtd_fc_30d         0
qtd_fo_7d          0
qtd_fo_30d         0
qtd_lsd_7d         0
qtd_lsd_30d        0
qtd_oa_7d          0
qtd_oa_30d         0
qtd_obs_7d         0
qtd_obs_30d        0
qtd_rce_7d         0
qtd_rce_30d        0
qtd_sts_7d         0
qtd_sts_30d        0
dtype: int64

In [87]:
# ==========================================
# DIAS COM ALGUM ALARME
# ==========================================

base_features["teve_alarme_dia"] = (
    base_features["qtd_alarmes_dia"] > 0
).astype(int)

In [88]:
for janela in [7, 30]:

    base_features[f"dias_com_alarme_{janela}d"] = (
        base_features
        .groupby("chave_porta")["teve_alarme_dia"]
        .transform(
            lambda x: x.shift(1)
            .rolling(
                janela,
                min_periods=1
            )
            .sum()
        )
    )

In [89]:
tipos_alarme = [
    coluna
    .replace("qtd_", "")
    .replace("_dia", "")
    for coluna in colunas_tipo_dia
]

tipos_alarme

['ca', 'csd', 'fc', 'fo', 'lsd', 'oa', 'obs', 'rce', 'sts']

In [90]:
colunas_tipos_7d = [
    f"qtd_{tipo}_7d"
    for tipo in tipos_alarme
]

colunas_tipos_30d = [
    f"qtd_{tipo}_30d"
    for tipo in tipos_alarme
]

In [91]:
base_features["tipos_alarme_7d"] = (
    base_features[colunas_tipos_7d]
    .gt(0)
    .sum(axis=1)
)

base_features["tipos_alarme_30d"] = (
    base_features[colunas_tipos_30d]
    .gt(0)
    .sum(axis=1)
)

In [92]:
base_features["alarmes_por_dia_ativo_7d"] = (
    base_features["qtd_alarmes_7d"]
    /
    base_features["dias_com_alarme_7d"].replace(0, pd.NA)
)

base_features["alarmes_por_dia_ativo_30d"] = (
    base_features["qtd_alarmes_30d"]
    /
    base_features["dias_com_alarme_30d"].replace(0, pd.NA)
)

In [93]:
base_features[
    [
        "alarmes_por_dia_ativo_7d",
        "alarmes_por_dia_ativo_30d"
    ]
] = (
    base_features[
        [
            "alarmes_por_dia_ativo_7d",
            "alarmes_por_dia_ativo_30d"
        ]
    ]
    .fillna(0)
    .astype(float)
)

In [94]:
base_features["media_alarmes_7d"] = (
    base_features["qtd_alarmes_7d"] / 7
)

base_features["media_alarmes_30d"] = (
    base_features["qtd_alarmes_30d"] / 30
)

In [95]:
base_features["aceleracao_alarmes_7d_30d"] = (
    base_features["media_alarmes_7d"]
    /
    (base_features["media_alarmes_30d"] + 1)
)

In [96]:
novas_features = [
    "dias_com_alarme_7d",
    "dias_com_alarme_30d",
    "tipos_alarme_7d",
    "tipos_alarme_30d",
    "alarmes_por_dia_ativo_7d",
    "alarmes_por_dia_ativo_30d",
    "media_alarmes_7d",
    "media_alarmes_30d",
    "aceleracao_alarmes_7d_30d"
]

print(
    base_features[
        novas_features
    ].describe().T
)

print("\nValores ausentes:")
print(
    base_features[
        novas_features
    ].isna().sum()
)

                              count      mean       std  min  25%  50%  \
dias_com_alarme_7d         522144.0  0.609330  1.257335  0.0  0.0  0.0
dias_com_alarme_30d        522144.0  2.583077  4.558168  0.0  0.0  0.0
tipos_alarme_7d            522662.0  1.286346  2.448457  0.0  0.0  0.0
tipos_alarme_30d           522662.0  3.073455  3.408391  0.0  0.0  0.0
alarmes_por_dia_ativo_7d   522662.0  1.867516  7.051463  0.0  0.0  0.0
alarmes_por_dia_ativo_30d  522662.0  3.451101  7.767893  0.0  0.0  0.0
media_alarmes_7d           522662.0  0.654603  3.985285  0.0  0.0  0.0
media_alarmes_30d          522662.0  0.642829  2.694507  0.0  0.0  0.0
aceleracao_alarmes_7d_30d  522662.0  0.199922  0.423693  0.0  0.0  0.0

                                75%         max
dias_com_alarme_7d         1.000000    7.000000
dias_com_alarme_30d        3.000000   30.000000
tipos_alarme_7d            2.000000    8.000000
tipos_alarme_30d           7.000000    8.000000
alarmes_por_dia_ativo_7d   2.000000  516.000000
alarmes_por_dia_ativo_30d  5.285714  474.000000
media_alarmes_7d           0.285714  283.142857
media_alarmes_30d          0.533333  137.100000
aceleracao_alarmes_7d_30d  0.204082    4.162233

Valores ausentes:
dias_com_alarme_7d           518
dias_com_alarme_30d          518
tipos_alarme_7d                0
tipos_alarme_30d               0
alarmes_por_dia_ativo_7d       0
alarmes_por_dia_ativo_30d      0
media_alarmes_7d               0
media_alarmes_30d              0
aceleracao_alarmes_7d_30d      0
dtype: int64

In [97]:
# ==========================================
# CORRIGIR DIAS COM ALARME
# ==========================================

historico_dias_alarme = base_target[
    ["chave_porta", "data"]
].copy()

historico_dias_alarme = historico_dias_alarme.merge(
    alarmes_diarios,
    on=["chave_porta", "data"],
    how="left"
)

historico_dias_alarme["qtd_alarmes_dia"] = (
    historico_dias_alarme["qtd_alarmes_dia"]
    .fillna(0)
)

historico_dias_alarme["teve_alarme_dia"] = (
    historico_dias_alarme["qtd_alarmes_dia"] > 0
).astype(int)

historico_dias_alarme = historico_dias_alarme.sort_values(
    ["chave_porta", "data"]
).reset_index(drop=True)

In [98]:
for janela in [7, 30]:

    historico_dias_alarme[
        f"dias_com_alarme_{janela}d"
    ] = (
        historico_dias_alarme
        .groupby("chave_porta")["teve_alarme_dia"]
        .transform(
            lambda x: x.shift(1)
            .rolling(
                janela,
                min_periods=1
            )
            .sum()
        )
    )

In [99]:
historico_dias_alarme = (
    historico_dias_alarme[
        historico_dias_alarme["data"]
        >= data_inicio_modelo_efetivo
    ][
        [
            "chave_porta",
            "data",
            "dias_com_alarme_7d",
            "dias_com_alarme_30d"
        ]
    ]
    .copy()
)

In [100]:
base_features = base_features.drop(
    columns=[
        "dias_com_alarme_7d",
        "dias_com_alarme_30d"
    ],
    errors="ignore"
)

base_features = base_features.merge(
    historico_dias_alarme,
    on=["chave_porta", "data"],
    how="left"
)

In [101]:
base_features["alarmes_por_dia_ativo_7d"] = (
    base_features["qtd_alarmes_7d"]
    /
    base_features["dias_com_alarme_7d"].replace(0, pd.NA)
)

base_features["alarmes_por_dia_ativo_30d"] = (
    base_features["qtd_alarmes_30d"]
    /
    base_features["dias_com_alarme_30d"].replace(0, pd.NA)
)

base_features[
    [
        "alarmes_por_dia_ativo_7d",
        "alarmes_por_dia_ativo_30d"
    ]
] = (
    base_features[
        [
            "alarmes_por_dia_ativo_7d",
            "alarmes_por_dia_ativo_30d"
        ]
    ]
    .fillna(0)
    .astype(float)
)

In [102]:
print(
    base_features[
        [
            "dias_com_alarme_7d",
            "dias_com_alarme_30d",
            "alarmes_por_dia_ativo_7d",
            "alarmes_por_dia_ativo_30d"
        ]
    ].isna().sum()
)

dias_com_alarme_7d           0
dias_com_alarme_30d          0
alarmes_por_dia_ativo_7d     0
alarmes_por_dia_ativo_30d    0
dtype: int64

In [103]:
# ==========================================
# TEMPO DESDE O ÚLTIMO ALARME
# ==========================================

historico_recencia = base_target[
    ["chave_porta", "data"]
].copy()

historico_recencia = historico_recencia.merge(
    alarmes_diarios,
    on=["chave_porta", "data"],
    how="left"
)

historico_recencia["qtd_alarmes_dia"] = (
    historico_recencia["qtd_alarmes_dia"]
    .fillna(0)
)

historico_recencia = historico_recencia.sort_values(
    ["chave_porta", "data"]
).reset_index(drop=True)

In [104]:
historico_recencia["data_com_alarme"] = (
    historico_recencia["data"]
    .where(
        historico_recencia["qtd_alarmes_dia"] > 0
    )
)

In [105]:
historico_recencia["data_ultimo_alarme"] = (
    historico_recencia
    .groupby("chave_porta")["data_com_alarme"]
    .transform(
        lambda x: x.shift(1).ffill()
    )
)

In [106]:
historico_recencia["dias_desde_ultimo_alarme"] = (
    historico_recencia["data"]
    - historico_recencia["data_ultimo_alarme"]
).dt.days

In [107]:
historico_recencia["sem_alarme_anterior"] = (
    historico_recencia["data_ultimo_alarme"]
    .isna()
    .astype(int)
)

In [108]:
historico_recencia = historico_recencia[
    historico_recencia["data"] >= data_inicio_modelo_efetivo
][
    [
        "chave_porta",
        "data",
        "dias_desde_ultimo_alarme",
        "sem_alarme_anterior"
    ]
].copy()

In [109]:
base_features = base_features.merge(
    historico_recencia,
    on=["chave_porta", "data"],
    how="left"
)

In [110]:
print(
    base_features[
        [
            "dias_desde_ultimo_alarme",
            "sem_alarme_anterior"
        ]
    ].describe()
)

print("\nSem alarme anterior:")
print(
    base_features["sem_alarme_anterior"]
    .value_counts()
)

print("\nValores ausentes:")
print(
    base_features[
        [
            "dias_desde_ultimo_alarme",
            "sem_alarme_anterior"
        ]
    ].isna().sum()
)

       dias_desde_ultimo_alarme  sem_alarme_anterior
count             378731.000000        522662.000000
mean                  62.713876             0.275381
std                  149.174391             0.446706
min                    1.000000             0.000000
25%                    4.000000             0.000000
50%                   13.000000             0.000000
75%                   43.000000             1.000000
max                 1036.000000             1.000000

Sem alarme anterior:
sem_alarme_anterior
0    378731
1    143931
Name: count, dtype: int64

Valores ausentes:
dias_desde_ultimo_alarme    143931
sem_alarme_anterior              0
dtype: int64

In [111]:
# ==========================================
# HISTÓRICO DE FALHAS ZM01 DA PORTA
# ==========================================

falhas_historicas = (
    eventos_falha[
        [
            "chave_porta",
            "inicio_avaria_datetime_emergencial"
        ]
    ]
    .copy()
)

falhas_historicas["data_falha"] = (
    pd.to_datetime(
        falhas_historicas["inicio_avaria_datetime_emergencial"]
    )
    .dt.normalize()
)

falhas_historicas = (
    falhas_historicas
    .drop_duplicates(
        subset=[
            "chave_porta",
            "inicio_avaria_datetime_emergencial"
        ]
    )
    .sort_values(
        [
            "chave_porta",
            "inicio_avaria_datetime_emergencial"
        ]
    )
    .reset_index(drop=True)
)

print("Eventos históricos de falha:")
print(len(falhas_historicas))

display(falhas_historicas.head())

Eventos históricos de falha:
3057

  chave_porta inicio_avaria_datetime_emergencial data_falha
0  BUT_P1_D01                2023-02-12 10:35:00 2023-02-12
1  BUT_P1_D01                2024-01-21 12:22:00 2024-01-21
2  BUT_P1_D01                2024-06-17 05:45:00 2024-06-17
3  BUT_P1_D01                2024-09-01 16:16:00 2024-09-01
4  BUT_P1_D01                2024-11-27 20:04:00 2024-11-27

In [112]:
print("\nIntervalo temporal:")
print(
    falhas_historicas[
        "inicio_avaria_datetime_emergencial"
    ].min()
)

print(
    falhas_historicas[
        "inicio_avaria_datetime_emergencial"
    ].max()
)

print("\nFalhas por porta:")
print(
    falhas_historicas
    .groupby("chave_porta")
    .size()
    .describe()
)

print("\nPortas com pelo menos uma falha:")
print(
    falhas_historicas[
        "chave_porta"
    ].nunique()
)

Intervalo temporal:
2023-01-01 02:39:00
2026-04-01 22:43:00

Falhas por porta:
count    491.000000
mean       6.226069
std        3.845991
min        1.000000
25%        3.000000
50%        6.000000
75%        8.000000
max       23.000000
dtype: float64

Portas com pelo menos uma falha:
491

In [113]:
# ==========================================
# FALHAS HISTÓRICAS POR PORTA E DIA
# ==========================================

falhas_dia = (
    falhas_historicas
    .groupby(
        ["chave_porta", "data_falha"]
    )
    .size()
    .reset_index(
        name="qtd_falhas_dia"
    )
)

falhas_dia = falhas_dia.rename(
    columns={
        "data_falha": "data"
    }
)

display(falhas_dia.head())

  chave_porta       data  qtd_falhas_dia
0  BUT_P1_D01 2023-02-12               1
1  BUT_P1_D01 2024-01-21               1
2  BUT_P1_D01 2024-06-17               1
3  BUT_P1_D01 2024-09-01               1
4  BUT_P1_D01 2024-11-27               1

In [114]:
historico_falhas = base_target[
    ["chave_porta", "data"]
].copy()

historico_falhas = historico_falhas.merge(
    falhas_dia,
    on=["chave_porta", "data"],
    how="left"
)

historico_falhas["qtd_falhas_dia"] = (
    historico_falhas["qtd_falhas_dia"]
    .fillna(0)
)

historico_falhas = historico_falhas.sort_values(
    ["chave_porta", "data"]
).reset_index(drop=True)

In [115]:
historico_falhas["qtd_falhas_30d"] = (
    historico_falhas
    .groupby("chave_porta")["qtd_falhas_dia"]
    .transform(
        lambda x: x.shift(1)
        .rolling(
            30,
            min_periods=1
        )
        .sum()
    )
)

historico_falhas["qtd_falhas_90d"] = (
    historico_falhas
    .groupby("chave_porta")["qtd_falhas_dia"]
    .transform(
        lambda x: x.shift(1)
        .rolling(
            90,
            min_periods=1
        )
        .sum()
    )
)

In [116]:
historico_falhas["qtd_falhas_anteriores"] = (
    historico_falhas
    .groupby("chave_porta")["qtd_falhas_dia"]
    .transform(
        lambda x: x.shift(1)
        .fillna(0)
        .cumsum()
    )
)

In [117]:
historico_falhas["data_com_falha"] = (
    historico_falhas["data"]
    .where(
        historico_falhas["qtd_falhas_dia"] > 0
    )
)

historico_falhas["data_ultima_falha"] = (
    historico_falhas
    .groupby("chave_porta")["data_com_falha"]
    .transform(
        lambda x: x.shift(1).ffill()
    )
)

historico_falhas["dias_desde_ultima_falha"] = (
    historico_falhas["data"]
    - historico_falhas["data_ultima_falha"]
).dt.days

historico_falhas["sem_falha_anterior"] = (
    historico_falhas["data_ultima_falha"]
    .isna()
    .astype(int)
)

In [118]:
historico_falhas = historico_falhas[
    historico_falhas["data"]
    >= data_inicio_modelo_efetivo
][
    [
        "chave_porta",
        "data",
        "qtd_falhas_30d",
        "qtd_falhas_90d",
        "qtd_falhas_anteriores",
        "dias_desde_ultima_falha",
        "sem_falha_anterior"
    ]
].copy()

base_features = base_features.merge(
    historico_falhas,
    on=["chave_porta", "data"],
    how="left"
)

In [119]:
colunas_falha_historica = [
    "qtd_falhas_30d",
    "qtd_falhas_90d",
    "qtd_falhas_anteriores",
    "dias_desde_ultima_falha",
    "sem_falha_anterior"
]

print(
    base_features[
        colunas_falha_historica
    ].describe().T
)

print("\nValores ausentes:")
print(
    base_features[
        colunas_falha_historica
    ].isna().sum()
)

print("\nSem falha anterior:")
print(
    base_features[
        "sem_falha_anterior"
    ].value_counts()
)

                            count        mean         std  min   25%    50%  \
qtd_falhas_30d           522662.0    0.140033    0.458867  0.0   0.0    0.0
qtd_falhas_90d           522662.0    0.411830    0.830865  0.0   0.0    0.0
qtd_falhas_anteriores    522662.0    2.614870    2.789658  0.0   0.0    2.0
dias_desde_ultima_falha  388167.0  191.209041  185.989361  1.0  53.0  130.0
sem_falha_anterior       522662.0    0.257327    0.437161  0.0   0.0    0.0

                           75%     max
qtd_falhas_30d             0.0    15.0
qtd_falhas_90d             1.0    16.0
qtd_falhas_anteriores      4.0    23.0
dias_desde_ultima_falha  272.0  1038.0
sem_falha_anterior         1.0     1.0

Valores ausentes:
qtd_falhas_30d                  0
qtd_falhas_90d                  0
qtd_falhas_anteriores           0
dias_desde_ultima_falha    134495
sem_falha_anterior              0
dtype: int64

Sem falha anterior:
sem_falha_anterior
0    388167
1    134495
Name: count, dtype: int64

In [120]:
# ==========================================
# PREPARAÇÃO DO HISTÓRICO ZM02
# CORRETIVAS PROGRAMADAS
# ==========================================

eventos_programada = programada[
    programada["chave_porta"].notna()
    & programada["inicio_avaria_datetime_programada"].notna()
].copy()

eventos_programada["data_programada"] = (
    pd.to_datetime(
        eventos_programada["inicio_avaria_datetime_programada"],
        errors="coerce"
    )
    .dt.normalize()
)

eventos_programada = (
    eventos_programada
    .drop_duplicates(
        subset=[
            "chave_porta",
            "inicio_avaria_datetime_programada"
        ]
    )
    .sort_values(
        [
            "chave_porta",
            "inicio_avaria_datetime_programada"
        ]
    )
    .reset_index(drop=True)
)

print("Eventos ZM02 em nível de porta:")
print(len(eventos_programada))

print("\nPortas com pelo menos uma ZM02:")
print(
    eventos_programada["chave_porta"].nunique()
)

print("\nPeríodo:")
print(
    eventos_programada[
        "inicio_avaria_datetime_programada"
    ].min()
)
print(
    eventos_programada[
        "inicio_avaria_datetime_programada"
    ].max()
)

print("\nQuantidade de ZM02 por porta:")
print(
    eventos_programada
    .groupby("chave_porta")
    .size()
    .describe()
)

Eventos ZM02 em nível de porta:
996

Portas com pelo menos uma ZM02:
390

Período:
2023-01-03 03:55:59
2026-03-28 14:15:00

Quantidade de ZM02 por porta:
count    390.000000
mean       2.553846
std        1.763941
min        1.000000
25%        1.000000
50%        2.000000
75%        3.000000
max       10.000000
dtype: float64

In [121]:
colunas_modelo = [
    # Contexto da porta
    "estacao",
    "plataforma",

    # Volume histórico de alarmes
    "qtd_alarmes_1d",
    "qtd_alarmes_3d",
    "qtd_alarmes_7d",
    "qtd_alarmes_30d",

    # Tipos de alarmes recentes
    "qtd_ca_7d",
    "qtd_csd_7d",
    "qtd_fc_7d",
    "qtd_fo_7d",
    "qtd_lsd_7d",
    "qtd_oa_7d",
    "qtd_obs_7d",
    "qtd_rce_7d",
    "qtd_sts_7d",

    # Comportamento recente
    "dias_com_alarme_7d",
    "tipos_alarme_7d",

    # Histórico de falhas
    "qtd_falhas_30d",
    "qtd_falhas_90d",
    "qtd_falhas_anteriores",
    "sem_falha_anterior",

    # Data será usada para o split temporal
    "data",

    # Target
    "falha_emergencial_7d"
]

dataset_modelo = base_features[
    colunas_modelo
].copy()

In [122]:
print("Shape:")
print(dataset_modelo.shape)

print("\nTipos:")
print(dataset_modelo.dtypes)

print("\nValores ausentes:")
print(dataset_modelo.isna().sum())

print("\nTarget:")
print(
    dataset_modelo["falha_emergencial_7d"]
    .value_counts(normalize=True)
    .mul(100)
    .round(2)
)

Shape:
(522662, 23)

Tipos:
estacao                          string
plataforma                       string
qtd_alarmes_1d                  float64
qtd_alarmes_3d                  float64
qtd_alarmes_7d                  float64
qtd_alarmes_30d                 float64
qtd_ca_7d                       float64
qtd_csd_7d                      float64
qtd_fc_7d                       float64
qtd_fo_7d                       float64
qtd_lsd_7d                      float64
qtd_oa_7d                       float64
qtd_obs_7d                      float64
qtd_rce_7d                      float64
qtd_sts_7d                      float64
dias_com_alarme_7d              float64
tipos_alarme_7d                   int64
qtd_falhas_30d                  float64
qtd_falhas_90d                  float64
qtd_falhas_anteriores           float64
sem_falha_anterior                int64
data                     datetime64[us]
falha_emergencial_7d              int64
dtype: object

Valores ausentes:
estacao                  0
plataforma               0
qtd_alarmes_1d           0
qtd_alarmes_3d           0
qtd_alarmes_7d           0
qtd_alarmes_30d          0
qtd_ca_7d                0
qtd_csd_7d               0
qtd_fc_7d                0
qtd_fo_7d                0
qtd_lsd_7d               0
qtd_oa_7d                0
qtd_obs_7d               0
qtd_rce_7d               0
qtd_sts_7d               0
dias_com_alarme_7d       0
tipos_alarme_7d          0
qtd_falhas_30d           0
qtd_falhas_90d           0
qtd_falhas_anteriores    0
sem_falha_anterior       0
data                     0
falha_emergencial_7d     0
dtype: int64

Target:
falha_emergencial_7d
0    97.17
1     2.83
Name: proportion, dtype: float64