In [4]:
import pandas as pd

caminho_1 = "../../data/Corretiva Programada/Ordens do SAP -Corretiva programada (ZM02).XLSX"
caminho_2 = "../../data/Corretiva Programada/Ordens do SAP -Corretiva programada (ZM02)- 2.XLSX"

df_1 = pd.read_excel(caminho_1, sheet_name="Sheet1")
df_2 = pd.read_excel(caminho_2, sheet_name="Sheet1")

print("Arquivo 1:", df_1.shape)
print("Arquivo 2:", df_2.shape)
print("Mesmas colunas:", df_1.columns.equals(df_2.columns))

Arquivo 1: (1163, 28)
Arquivo 2: (1163, 28)
Mesmas colunas: True

In [5]:
df = df_1.copy()
print(f"Linhas: {df.shape[0]}")
print(f"Colunas: {df.shape[1]}")

df.head()

Linhas: 1163
Colunas: 28

,Tipo de Nota,Nota,Ordem,Indisponível,Falha,IQM,Analisada,Comentários Classificação Engenharia,Perfil do catálogo,Descrição,...,Centro de Trabalho Responsável,Sintoma,Objeto,Defeito,Causa,Ação,Data Análise,Hora Análise,Encerram.por Data,Hora de Encerramento
0,Z2,15069252,54081268.0,NaN,NaN,NaN,NaN,NaN,6PSD,Porta PCC-PSD a,...,SP04IBUT,PDM NÃO ABRE,"ESTRUTURA, ACABAMENTO, E ACESSÓRIOS DO P",PORTA DESAJUSTADA,FALTA FIXACAO,FIXADO,NaT,00:00:00,2026-01-25,16:50:18
1,Z2,14647619,53659484.0,NaN,NaN,NaN,NaN,NaN,6PSD,PDMs plat 1 e 2 com falha momentânea.,...,SP04IBUT,MAU CONTATO,SWITCK DE COMUNICAÇÃO,SEM CONEXAO ELETRICA,ERRO DE SOFTWARE,RESETADO E TESTADO,NaT,00:00:00,2025-06-01,04:36:44
2,Z2,14682623,53694340.0,NaN,NaN,NaN,NaN,NaN,6PSD,Rele painel SSE intermitente,...,SP04IBUT,FACHADA PSD SEM ALIMENTAÇÃO,DISPOSITIVO DE PROTECAO,CONVERSOR DE TENSAO AVARIADO,OPERACAO INDEVIDA,SUBSTITUIDO(A),NaT,00:00:00,2025-06-19,05:10:12
3,Z2,14864269,53874165.0,NaN,NaN,NaN,NaN,NaN,6PSD,Multimedidor SSE moldura solta,...,SP04IBUT,ESTRUTURA DANIFICADA,MULTIMEDIDOR,VIDRO QUEBRADO,DESGASTE,SUBSTITUIDO(A),NaT,00:00:00,2025-09-30,14:53:22
4,Z2,13390549,52423535.0,NaN,NaN,NaN,NaN,NaN,6PSD,Volume do P.A baixo.,...,SP04IBUT,SERVIDOR SEM COMUNICACAO,SWITCK DE COMUNICAÇÃO,BAIXA ISOLACAO,FALTA FIXACAO,APERTADO(A),NaT,00:00:00,2023-07-27,13:52:02

In [6]:
print("Conteúdo exatamente igual:", df_1.equals(df_2))

Conteúdo exatamente igual: True

In [7]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1163 entries, 0 to 1162
Data columns (total 28 columns):
 #   Column                                Non-Null Count  Dtype
---  ------                                --------------  -----
 0   Tipo de Nota                          1163 non-null   str
 1   Nota                                  1163 non-null   int64
 2   Ordem                                 1158 non-null   float64
 3   Indisponível                          1 non-null      str
 4   Falha                                 0 non-null      float64
 5   IQM                                   0 non-null      float64
 6   Analisada                             1 non-null      str
 7   Comentários Classificação Engenharia  1 non-null      str
 8   Perfil do catálogo                    1163 non-null   str
 9   Descrição                             1163 non-null   str
 10  Local de Instalação                   1163 non-null   str
 11  Status do Usuário da Ordem            1158 non-null   str
 12  Texto Longo da Ordem                  1156 non-null   str
 13  Status do Sistema da Ordem            1158 non-null   str
 14  Início avaria                         1163 non-null   str
 15  Hora início avaria                    1163 non-null   object
 16  Fim da avaria                         1124 non-null   str
 17  Hora do fim da avaria                 1163 non-null   object
 18  Centro de Trabalho Responsável        1163 non-null   str
 19  Sintoma                               1163 non-null   str
 20  Objeto                                1124 non-null   str
 21  Defeito                               1124 non-null   str
 22  Causa                                 1121 non-null   str
 23  Ação                                  1120 non-null   str
 24  Data Análise                          1 non-null      datetime64[us]
 25  Hora Análise                          1163 non-null   object
 26  Encerram.por Data                     1156 non-null   datetime64[us]
 27  Hora de Encerramento                  1163 non-null   object
dtypes: datetime64[us](2), float64(3), int64(1), object(4), str(18)
memory usage: 254.5+ KB

In [8]:
relatorio_ausentes = pd.DataFrame({
    "quantidade": df.isna().sum(),
    "percentual": (df.isna().mean() * 100).round(2)
}).sort_values("percentual", ascending=False)

relatorio_ausentes[
    relatorio_ausentes["quantidade"] > 0
]

                                      quantidade  percentual
IQM                                         1163      100.00
Falha                                       1163      100.00
Indisponível                                1162       99.91
Analisada                                   1162       99.91
Comentários Classificação Engenharia        1162       99.91
Data Análise                                1162       99.91
Ação                                          43        3.70
Causa                                         42        3.61
Fim da avaria                                 39        3.35
Defeito                                       39        3.35
Objeto                                        39        3.35
Encerram.por Data                              7        0.60
Texto Longo da Ordem                           7        0.60
Status do Sistema da Ordem                     5        0.43
Status do Usuário da Ordem                     5        0.43
Ordem                                          5        0.43

In [9]:
diagnostico_identificadores = pd.Series({
    "linhas": len(df),
    "notas_ausentes": df["Nota"].isna().sum(),
    "notas_distintas": df["Nota"].nunique(dropna=True),
    "notas_repetidas_excedentes": (
        df["Nota"].notna() & df["Nota"].duplicated()
    ).sum(),
    "ordens_ausentes": df["Ordem"].isna().sum(),
    "ordens_distintas": df["Ordem"].nunique(dropna=True),
    "ordens_repetidas_excedentes": (
        df["Ordem"].notna() & df["Ordem"].duplicated()
    ).sum(),
    "linhas_totalmente_duplicadas": df.duplicated().sum()
})

diagnostico_identificadores

linhas                          1163
notas_ausentes                     0
notas_distintas                 1158
notas_repetidas_excedentes         5
ordens_ausentes                    5
ordens_distintas                1153
ordens_repetidas_excedentes        5
linhas_totalmente_duplicadas       0
dtype: int64

In [12]:
colunas_criticas = [
    "Indisponível",
    "Falha",
    "IQM",
    "Analisada",
    "Comentários Classificação Engenharia",
    "Data Análise"
]

for coluna in colunas_criticas:
    print(f"\n--- {coluna} ---")
    print(df[coluna].value_counts(dropna=False))

--- Indisponível ---
Indisponível
NaN    1162
X         1
Name: count, dtype: int64

--- Falha ---
Falha
NaN    1163
Name: count, dtype: int64

--- IQM ---
IQM
NaN    1163
Name: count, dtype: int64

--- Analisada ---
Analisada
NaN    1162
X         1
Name: count, dtype: int64

--- Comentários Classificação Engenharia ---
Comentários Classificação Engenharia
NaN           1162
 NC/ RESET       1
Name: count, dtype: int64

--- Data Análise ---
Data Análise
NaT           1162
2026-03-04       1
Name: count, dtype: int64

In [13]:
df.loc[df["Ordem"].isna(), 
       ["Nota",
        "Ordem",
        "Descrição",
        "Local de Instalação",
        "Status do Usuário da Ordem",
        "Status do Sistema da Ordem",
        "Início avaria",
        "Fim da avaria"]]

,Nota,Ordem,Descrição,Local de Instalação,Status do Usuário da Ordem,Status do Sistema da Ordem,Início avaria,Fim da avaria
97,14795035,NaN,MCP PSD-FAL-PLT2-PP05PDM,SP04-6-PSD-FAL-PLT2-PP05PDM,NaN,NaN,22/08/2025,NaN
131,15037814,NaN,VENTILADOR CENTRIF 220W HOR R2E250RA4301,SP04-6-PSD-FAL-SLBT-PCC,NaN,NaN,08/01/2026,NaN
147,14363556,NaN,CONJUNTO COMPLETO DO TROLLEY PSD,SP04-6-PSD-FRA-PLT1-PP10PDM,NaN,NaN,29/12/2024,NaN
837,13327708,NaN,DOOR CONTROL MODULE-MCP,SP04-6-PSD-PIN-PLT2-PP06PDM,NaN,NaN,16/06/2023,16/06/2023
1028,13114749,NaN,DOOR CONTROL,SP04-6-PSD-REP-PLT1-PP16PDM,NaN,NaN,14/02/2023,NaN

In [14]:
df_limpo = df.copy()
df_limpo["linha_origem"] = df_limpo.index + 2

In [15]:
import re
import unicodedata

def normalizar_coluna(nome):
    nome = str(nome).strip().lower()
    nome = unicodedata.normalize("NFKD", nome)
    nome = nome.encode("ascii", "ignore").decode("ascii")
    nome = re.sub(r"[^a-z0-9]+", "_", nome)
    return nome.strip("_")

df_limpo.columns = [
    normalizar_coluna(coluna)
    for coluna in df_limpo.columns
]

print("Colunas duplicadas:", df_limpo.columns.duplicated().sum())
df_limpo.columns.tolist()

Colunas duplicadas: 0

['tipo_de_nota',
 'nota',
 'ordem',
 'indisponivel',
 'falha',
 'iqm',
 'analisada',
 'comentarios_classificacao_engenharia',
 'perfil_do_catalogo',
 'descricao',
 'local_de_instalacao',
 'status_do_usuario_da_ordem',
 'texto_longo_da_ordem',
 'status_do_sistema_da_ordem',
 'inicio_avaria',
 'hora_inicio_avaria',
 'fim_da_avaria',
 'hora_do_fim_da_avaria',
 'centro_de_trabalho_responsavel',
 'sintoma',
 'objeto',
 'defeito',
 'causa',
 'acao',
 'data_analise',
 'hora_analise',
 'encerram_por_data',
 'hora_de_encerramento',
 'linha_origem']

In [16]:
for coluna in ["nota", "ordem"]:
    df_limpo[coluna] = (
        df_limpo[coluna]
        .astype("string")
        .str.strip()
        .str.replace(r"\.0$", "", regex=True)
    )

df_limpo[["nota", "ordem"]].dtypes

nota     string
ordem    string
dtype: object

In [17]:
colunas_totalmente_vazias = [
    coluna
    for coluna in df_limpo.columns
    if df_limpo[coluna].isna().all()
]

colunas_totalmente_vazias

['falha', 'iqm']

In [18]:
df_limpo.drop(
    columns=colunas_totalmente_vazias,
    inplace=True
)